--zonenames
DARKMOONFAIREZONE = "Darkmoon Island"
GORGROND = "Gorgrond"
AZSHARAZONE = "Azshara"
STORMWINDCITY = "Stormwind City"
BOREANTUNDRAZONE = "Borean Tundra"
DALARANZONE = "Dalaran"

SOMEBODYLIKESME=522
--achievement numbers;
GOTMYMINDHUNDRED=1176

HUNDREDFISH=1558
TWOFIFTYFISH=1559

EKOMADNESS=5443




--QUESTS
FIVEDUNGEON=4956
TWENTYDUNGEON=4957
FIFTYQUESTS = 503;
HUNDREDQUESTS = 504;
TWOFIFTYQUESTS=505
FIVEHUNDREDQUESTS=506
THOUSANDQUESTS=507
THREETHOUSANDQUESTS=978
JUSTLYREWARDED=5752
FIVEDAILYQUESTS=973
FIFTYDAILYQUESTS=974
TWOHUNDREDDAILIES=975
TWOTHOUSANDQUESTS=32
ASIMPLEREQUEST=31
HEMETNESINGWARYTHECOLLECTEDQUESTS=941
OFBLOODANDANGUISH=1576
THEBREADWINNER=1182
THELOREMASTER=7520

--feats of strength
THOUSANDDUNGEONEMBLEMS=3844
TWOFIVEHUNDREDDUNGEONEMBLEMS=4316
ABREWFASTMOUNT=3496
ATRIBUTETODEDICATEDINSANITY=4080
ATRIBUTETOIMMORTALITYA=4156
ATRIBUTETOIMMORTALITYH=4079
ATRIBUTETOINSANITY10=3810
ATRIBUTETOINSANITY25=3819
ATRIBUTETOMADSKILL10=3809
ATRIBUTETOMADSKILL25=3818
ATRIBUTETOSKILL10=3808
ATRIBUTETOSKILL25=3817
ANDILLFORMTHEHEAD=4626
ATIESH=425
AVASTYEADMIRAL=871
BIGLOVEROCKET=4627
CHAMPIONOFULDUAR=2903
CONQUEROROFULDUAR=2904
CUTTINGEDGEGRANDEMPRESS=7486
CUTTINGEDGESHA=7487
CUTTINGEDGEWILL=7485
DEADLIESTCATCH=560
DEATHCHARGERSREINS=729
DRAGONWRATH=5839
FANGSOFTHEFATHER=6181
GRANDBLACKWARMAMMOTH=2081
HEFEEDSONYOURTEARS10=3004
HEFEEDSONYOURTEARS25=3005
HERALDOFTHETITANS=3316
HEROOFSHATTRATH=1205
ICANTHEARYOUOVERTHESOUNDOFHOWAWESOMEIAM=5313
INSANEINTHEMEMBRANE=2336
INVINCIBLESREINS=4625
ONYXPANTHER=3896
REINSOFTHERAVENLORD=883
SCOUREROFTHEETERNALSANDS=5767
SHADOWMOURNE=4623
SULFURAS=429
SWIFTWHITEHAWKSTRIDER=884
THEHORSEMANSREINS=980
THEIMMORTAL=2186
THEUNDYING=2187
THERAMORESFALLA=7467
THERAMORESFALLH=7468
THUNDERFURY=428
VALANYR=3142
VENOMHIDERAVASAUR=3357
WARGLAIVESOFAZZINOTH=426
WHYBECAUSEITSRED=424
WINTERSPRINGFROSTSABER=3356




--vanilla rep
ARGENTDAWN=946
THEYLOVEMEINTHATTUNNEL=944
HYDRAXIANWATERLORDS=955
BROODOFNOZDORMU=956


--general
GOINGDOWN=964
STABLEKEEPER=2141
SAFEDEPOSIT=546
GREEDY=558
CATACLYSMICALLYSUPERIOR=5373
NEEDY=559
BREAKINGTHESOUNDBARRIER=5180
LEVEL85=4826
SUPERIOR=557
GOTMYMINDONMYMONEY100=1176
GOTMYMINDONMYMONEY1000=1177
GOTMYMINDONMYMONEY5000=1178
SHAVEANDAHAIRCUT=545
LEVEL90=6193
DYNAMICDUO=7382
DOUBLEAGENT=7380
TENTABARDS=1020
EPIC=556
CATACLYSMICALLYEPIC=5372
MYSTICALLYSUPERIOR=6348
MYSTICALLYEPIC=6349
MYSACKISGIGANTIQUE=1165
SQUIRRELSWHOSHAREDMYLIFE=2557
SQUIRRELSWHOCAREDFORME=5548
SQUIRRELSIONCECARESSED=6350
FRIENDORFOWL=1254
HIGHERLEARNING=1956
YOULLFEELRIGHTASRAIN=5779
ARMOREDBROWNBEAR=2076
WOOLYMAMMOTH=2077
TRAVELERSTUNDRAMAMMOTH=2078
GETTOTHECHOPPA=2097
VIALOFTHESANDS=5749
GRANDEXPEDITIONYAK=7386
RINGOFTHEKIRINTOR=2084
FILLINGUPTHEBARN=2142
ONEHUMPORTWO=4888



--explore
EXPLORECATACLYSM=4868
EXPLOREEASTERNKINGDOMS=42
EXPLOREKALIMDOR=43
EXPLORENORTHREND=45
EXPLOREOUTLAND=44
--argent tournament
ARGENTVALOR=2758
TILTED=2772
LANCEALOT=2836
ITSJUSTAFLESHWOUND=2773
PONYUP=3736
CHAMPIONOFORGRIMMAR=2783
CHAMPIONOFSENJIN=2784
CHAMPIONOFSILVERMOON=2785
CHAMPIONOFTB=2786
CHAMPIONOFUNDERCITY=2787
CHAMPIONOFTHEHORDE=2788
CHAMPIONOFTHEALLIANCE=2782
SUNREAVERS=3677
SWORDINTHESKULL=4596
CHAMPIONOFDARNASSUS=2777
CHAMPIONOFEXODAR=2778
CHAMPIONOFGNOMEREGAN=2779
CHAMPIONOFIRONFORGE=2780
CHAMPIONOFSTORMWIND=2781
ASILVERCONFIDANT=3676




--PROFESSIONS
PROFESSIONALGRANDMASTER=734
PROFESSIONALILLUSTRIOUSGRANDMASTER=4924
WORKINGDAYANDNIGHT=735
SKILLSTOPAYTHEBILLS=730
JACKOFALLTRADES=7378


--first aid
ULTIMATETRIAGE=141
ILLUSTRIOUSGRANDMASTER=4918
ZENMASTERMEDIC=6838
PREPARINGFORDISASTER=5480


--REP

TENEXALTED=524
AMBASSADOROFTHEHORDE=762
AMBASSADOROFTHEALLIANCE=948
TIMEFLIESWHENYOUREHAVINGFUN=5794
FIFTEENEXALTED=521
DIPLOMATH=943
DIPLOMATA=942
ARGENTCHAMPION=945
GUARDIANOFCENARIUS=953




--general
DUALSPEC=2716
FASTANDFURIOUS=889
ITSHAPPYHOUR=1833
STABLEKEEPER=2141
TASTESLIKECHICKEN=1832
TOALLTHESQUIRRELSIVELOVED=1206
WELLREAD=1244
PESTCONTROL=2556



--professions
JOURNEYMANFIRSTAID=131
JOURNEYMANFISHING=126
JOURNEYMANCOOKING=121
PROFESSIONALJOURNEYMAN=116
PROFESSIONALEXPERT=731
GIDDYUP=891
EXPERTMEDIC=132
DIGGER=5315

TWENTYFIVEFISH = 1556;
FIFTYFISH = 1557;
FISHORCUTBAITSTORM = 5476;
FISHORCUTBAITORG = 5477;
FISHORCUTBAITDARN = 5848;
FISHORCUTBAITIRON = 5847;
FISHORCUTBAITTB = 5849;
FISHORCUTBAITUC = 5850;
FISHORCUTBAITALLY = 5851;
FISHORCUTBAITHORDE = 5852;
FISHINGTOURNAMENT = 306;
OLDGNOMEANDTHESEA=153
LIMNOLOGIST=5478
OCEANOGRAPHER=5479


LETSDOLUNCHSTORM = 5474;
LETSDOLUNCHDARN = 5842;
LETSDOLUNCHIRON = 5841;
LETSDOLUNCHORG = 5475;
LETSDOLUNCHTB = 5843
LETSDOLUNCHUC = 5844
LETSDOLUNCHALLY = 5845;
LETSDOLUNCHHORDE = 5846;
REPRESENT =621;


--cooking
COOKINGAWARD =1998;
TENCOOKINGAWARDS=1999
TWENTYFIVECOOKINGAWARDS=2000
FIFTYCOOKINGAWARDS=2001
LUNCHLADY=1795
ABUNCHOFLUNCH=5845
KICKINITUPANOTCH=906
SOUSCHEF=1798
GRANDMASTERCHEF=125
ILLUSTRIOUSGRANDMASTERCOOK=4916
MASTEROFTHEGRILL=7300
MASTEROFTHEWOK=7301
MASTEROFTHEPOT=7302
MASTEROFTHESTEAMER=7303
MASTEROFTHEOVEN=7304
MASTEROFTHEBREW=7305
NOWIAMTHEMASTER=7325
THECAKEISNOTALIE=877
THEOUTLANDGOURMET=1800
THENORTHRENDGOURMET=1777
THECATACLYSMICGOURMET=5472
THEPANDARENGOURMET=7326
DRAENORGOURMET=9501
HUNDREDCOOKINGAWARDS=2002
SECONDTHATEMOTION=1780
CRITTERGITTER=1781
DINNERIMPOSSIBLE=1785
CHEFDECUISINE=1799
COOKIHNGWITHSTYLE=3296
CAPTAINRUMSEYSLAGER=1801
OURDAILYBREADA=1782 --ALIANCE
OURDAILYBREADH=1783
HAILTOTHECHEF=1563
DROWNYOURSORROWS=5754
CATACLYSMICALLYDELICIOUS=5753
PANDARENCUISINE=7329
PANDARENDELICACIES=7330


--cooking achs


COOKINGACHS = {}
COOKINGACHS[COOKINGAWARD] = 1;
COOKINGACHS[TENCOOKINGAWARDS] = 1;
COOKINGACHS[TWENTYFIVECOOKINGAWARDS] = 1;
COOKINGACHS[FIFTYCOOKINGAWARDS] = 1;
COOKINGACHS[LUNCHLADY] = 1;
COOKINGACHS[ABUNCHOFLUNCH] = 1;
COOKINGACHS[KICKINITUPANOTCH] = 1;
COOKINGACHS[SOUSCHEF] = 1;
COOKINGACHS[GRANDMASTERCHEF] = 1;
COOKINGACHS[ILLUSTRIOUSGRANDMASTERCOOK] = 1;
COOKINGACHS[MASTEROFTHEGRILL] = 85;
COOKINGACHS[MASTEROFTHEWOK] = 85;
COOKINGACHS[MASTEROFTHEPOT] = 85;
COOKINGACHS[MASTEROFTHESTEAMER] = 85;
COOKINGACHS[MASTEROFTHEOVEN] = 85;
COOKINGACHS[MASTEROFTHEBREW] = 85;
COOKINGACHS[NOWIAMTHEMASTER] = 85;
COOKINGACHS[THECAKEISNOTALIE] = 1;
COOKINGACHS[THEOUTLANDGOURMET] = 60;
COOKINGACHS[THENORTHRENDGOURMET] = 60;
COOKINGACHS[THECATACLYSMICGOURMET] = 80;
COOKINGACHS[THEPANDARENGOURMET] = 85;
COOKINGACHS[HUNDREDCOOKINGAWARDS] = 1;
COOKINGACHS[SECONDTHATEMOTION] = 1;
COOKINGACHS[CRITTERGITTER] = 1;
COOKINGACHS[DINNERIMPOSSIBLE] = 1;
COOKINGACHS[CHEFDECUISINE] = 1;
COOKINGACHS[COOKIHNGWITHSTYLE] = 1;
COOKINGACHS[CAPTAINRUMSEYSLAGER] = 1;
COOKINGACHS[HAILTOTHECHEF] = 60; 
COOKINGACHS[DROWNYOURSORROWS] = 1; 
COOKINGACHS[CATACLYSMICALLYDELICIOUS] = 1; 
COOKINGACHS[PANDARENCUISINE] = 80; 
COOKINGACHS[PANDARENDELICACIES] = 80; 
COOKINGACHS[DRAENORGOURMET] = 80; 
COOKINGACHS[YOULLFEELRIGHTASRAIN] = 10;



--EXPLORE
BADLANDS =765
ELWYNN = 776;
DUROTAR = 728;
DUNMOROGH = 627;
TELDRASSIL =842;
AZUREMYST =860;
TIRISFAL=768;
MULGORE=736;
BESTART=859;
WESTFALL=802;
LOCHMODAN=779;
GHOSTLANDS=858;
SILVERPINE=769;
NORTHERNBARRENS=750;
DARKSHORE=844;
AZSHARA=852;
BLOODMYST=861;
REDRIDGE=780;
DUSKWOOD=778;
BURNINGSTEPPES=775;
BLASTEDLANDS=766;
WETLANDS=841;
ASHENVALEALLY=845;
STONETALONALLY=847;
ASHENVALEHORDE=845;
STONETALONHORDE=847;
HILLSBRAD=772;
ARATHI=761;
NORTHERNSTRANGLETHORN=781;
CAPEOFSTRANGLETHORN=4995;
HINTERLANDS=773;
DESOLACE=848;
DEADWINDPASS=777;
ISLEOFQUELDANAS=868;
EVERSONGWOODS =859
SWAMPOFSORROWS=782
SEARINGGORGE=774
SOUTHERNBARRENSA=4996;
SOUTHERNBARRENSH=4996;
FERALASA=849
FERALASH=849
THOUSANDNEEDLES=846
WINTERSPRING=857
FELWOOD=853
SILITHUS=856
TANARIS=851
UNGOROCRATER=854
MOONGLADE=855


DUSTWALLOWMARSHA=850
DUSTWALLOWMARSHH=850
WESTERNPLAGUELANDS=770
EASTERNPLAGUELANDS=771

--quests
BADLANDSQUESTS=4900
BLASTEDLANDSQUESTS=4909
BURNINGSTEPPESQUESTS=4901
SEARINGGORGEQUESTS=4910
SWAMPOFSORROWSQUESTS=4904
READYSETGOAT=5444

FELWOODQUESTS=4931
TANARISQUESTS=4935
UNGOROCRATERQUESTS=4939
WINTERSPRINGQUESTS=4940


--zone quests
ZONEQUESTS={};
ZONEQUESTS[WESTFALL]=4903
ZONEQUESTS[LOCHMODAN]=4899
ZONEQUESTS[GHOSTLANDS]=4908
ZONEQUESTS[SILVERPINE]=4894
ZONEQUESTS[NORTHERNBARRENS]=4933
ZONEQUESTS[DARKSHORE]=4928
GHOSTSINTHEDARK=5453
ZONEQUESTS[AZSHARA]=4927
JOYRIDE=5454
GLUTTONFIERY=5448
GLUTTONICY=5546
GLUTTONSHADOWY=5547
ZONEQUESTS[BLOODMYST]=4926

ZONEQUESTS[REDRIDGE]=4902;
ZONEQUESTS[DUSKWOOD]=4907;
ZONEQUESTS[WETLANDS]=4898;
ASHENVALEALLYQUESTS=4925;
STONETALONQUESTSALLY=4936;
ZONEQUESTS[ASHENVALEHORDE]=4976;
ZONEQUESTS[STONETALONHORDE]=4980;
ZONEQUESTS[HILLSBRAD]=4895;
ZONEQUESTS[ARATHI]=4896;
ZONEQUESTS[NORTHERNSTRANGLETHORN]=4906;
GREENHILLS=940;
ZONEQUESTS[HINTERLANDS] = 4897;
ZONEQUESTS[CAPEOFSTRANGLETHORN]= 4905
ZONEQUESTS[DESOLACE] =4930;
SOUTHERNBARRENSQUESTSA = 4937;
-- ZONEQUESTS[SOUTHERNBARRENSA] = 4937
ZONEQUESTS[SOUTHERNBARRENSH] = 4981
FERALASQUESTSA= 4932
ZONEQUESTS[FERALASH]= 4979
ZONEQUESTS[THOUSANDNEEDLES]= 4938
DUSTWALLOWMARSHQUESTSA= 4929
ZONEQUESTS[DUSTWALLOWMARSHH]= 4978
ZONEQUESTS[WESTERNPLAGUELANDS]= 4893
ZONEQUESTS[EASTERNPLAGUELANDS]= 4892
FULLCARAVAN = 5442
SILITHUSQUESTS = 4934
LOREMASTEROFEASTERNKINGDOMS=1676
LOREMASTEROFKALIMDOR=1678

--ARENA
STEPINTOTHEARENA = 397
WORLDWIDEWINNER = 699
JUSTTHETWOOFUS = 399
THREESCOMPANY = 402
HIGHFIVE = 406 --has lots of variants
HOTSTREAK = 408
HOTTERSTREAK = 1162
LASTMANSTANDING = 409
CHALLENGER =2090
RIVAL = 2093
DUELIST= 2092
GLADIATOR= 2091
ARENAMASTER= 1174
GURUBASHIARENAGRANDMASTER=396
GURUBASHIARENAMASTER=389

TOYINGAROUND = 9670

LEVELTENACHIEVEMENTS = {}
LEVELTENACHIEVEMENTS [REPRESENT] = 10
LEVELTENACHIEVEMENTS [COOKINGAWARD] = 10
LEVELTENACHIEVEMENTS [FIFTYQUESTS] = 10
LEVELTENACHIEVEMENTS [ASIMPLEREQUEST] = 10
LEVELTENACHIEVEMENTS [ABUNCHOFLUNCH] = 10
LEVELTENACHIEVEMENTS [FIFTYQUESTS] = 10
LEVELTENACHIEVEMENTS [FIVEDUNGEON] = 15
LEVELTENACHIEVEMENTS [FIVEDAILYQUESTS] = 15
LEVELTENACHIEVEMENTS [GIDDYUP] = 20
LEVELTENACHIEVEMENTS [DUALSPEC] = 30
LEVELTENACHIEVEMENTS [TWENTYDUNGEON] = 25
LEVELTENACHIEVEMENTS [SOMEBODYLIKESME] = 30
LEVELTENACHIEVEMENTS [LUNCHLADY] = 30
LEVELTENACHIEVEMENTS [FIFTYDAILYQUESTS] = 30
LEVELTENACHIEVEMENTS [FASTANDFURIOUS] = 40
LEVELTENACHIEVEMENTS [EXPERTMEDIC] = 50
LEVELTENACHIEVEMENTS [TWOFIFTYFISH] = 40
LEVELTENACHIEVEMENTS [PROFESSIONALEXPERT] = 50
LEVELTENACHIEVEMENTS [SOUSCHEF] = 65 --100 recipes
LEVELTENACHIEVEMENTS [TENEXALTED] = 60
LEVELTENACHIEVEMENTS [TWOHUNDREDDAILIES] = 60
LEVELTENACHIEVEMENTS [GURUBASHIARENAMASTER] = 60
LEVELTENACHIEVEMENTS [GURUBASHIARENAGRANDMASTER] = 70
LEVELTENACHIEVEMENTS [ILLUSTRIOUSGRANDMASTER] = 70 --first aid
LEVELTENACHIEVEMENTS [ZENMASTERMEDIC] = 80
LEVELTENACHIEVEMENTS [TOYINGAROUND] = 80



LEVELTENALLIANCEACHIEVEMENTS = {}
LEVELTENALLIANCEACHIEVEMENTS[FISHORCUTBAITSTORM] = 15
LEVELTENALLIANCEACHIEVEMENTS[LETSDOLUNCHSTORM] = 15
LEVELTENALLIANCEACHIEVEMENTS[FISHORCUTBAITIRON] = 20
LEVELTENALLIANCEACHIEVEMENTS[LETSDOLUNCHIRON] = 20
LEVELTENALLIANCEACHIEVEMENTS[FISHORCUTBAITDARN] = 25
LEVELTENALLIANCEACHIEVEMENTS[LETSDOLUNCHDARN] = 25
LEVELTENALLIANCEACHIEVEMENTS[AMBASSADOROFTHEALLIANCE] = 60



LEVELTENHORDEACHIEVEMENTS = {}
LEVELTENHORDEACHIEVEMENTS[FISHORCUTBAITORG] = 15
LEVELTENHORDEACHIEVEMENTS[LETSDOLUNCHORG] = 15
LEVELTENHORDEACHIEVEMENTS[FISHORCUTBAITTB] = 20
LEVELTENHORDEACHIEVEMENTS[LETSDOLUNCHTB] = 20
LEVELTENHORDEACHIEVEMENTS[FISHORCUTBAITUC] = 25
LEVELTENHORDEACHIEVEMENTS[LETSDOLUNCHUC] = 25
LEVELTENHORDEACHIEVEMENTS[AMBASSADOROFTHEHORDE] = 60

--needs to be in broadly level order.  split in 2
EKALLIANCEACHIEVEMENTS = {}
EKALLIANCEACHIEVEMENTS[ZONEQUESTS[WESTFALL]] = 10
EKALLIANCEACHIEVEMENTS[ZONEQUESTS[LOCHMODAN]] = 10
EKALLIANCEACHIEVEMENTS[WESTFALL] =15
EKALLIANCEACHIEVEMENTS[LOCHMODAN] =15
EKALLIANCEACHIEVEMENTS[ZONEQUESTS[REDRIDGE]] =20
EKALLIANCEACHIEVEMENTS[REDRIDGE] =20
EKALLIANCEACHIEVEMENTS[DUSKWOOD] =25
EKALLIANCEACHIEVEMENTS[WETLANDS] =25
EKALLIANCEACHIEVEMENTS[ASHENVALEALLYQUESTS] =25
EKALLIANCEACHIEVEMENTS[ASHENVALEALLY] =25


EKALLIANCETWO = {}
EKALLIANCETWO[ARATHI] =35
EKALLIANCETWO[ZONEQUESTS[ARATHI]] =35
EKALLIANCETWO[NORTHERNSTRANGLETHORN] =35
EKALLIANCETWO[ZONEQUESTS[NORTHERNSTRANGLETHORN]] =35
EKALLIANCETWO[GREENHILLS] =35
EKALLIANCETWO[CAPEOFSTRANGLETHORN] =40
EKALLIANCETWO[ZONEQUESTS[CAPEOFSTRANGLETHORN]] =40
EKALLIANCETWO[HINTERLANDS] =40
EKALLIANCETWO[ZONEQUESTS[HINTERLANDS]] =40
EKALLIANCETWO[EASTERNPLAGUELANDS] =40
EKALLIANCETWO[ZONEQUESTS[EASTERNPLAGUELANDS]] =40
EKALLIANCETWO[WESTERNPLAGUELANDS] =40
EKALLIANCETWO[ZONEQUESTS[WESTERNPLAGUELANDS]] =40
EKALLIANCETWO[FULLCARAVAN] =40
EKALLIANCETWO[SWAMPOFSORROWS] =60
EKALLIANCETWO[DEADWINDPASS] =60
EKALLIANCETWO[SEARINGGORGE] =60
EKALLIANCETWO[TIRISFAL] =60
EKALLIANCETWO[ISLEOFQUELDANAS] =59
EKALLIANCETWO[EVERSONGWOODS] =60
EKALLIANCETWO[GHOSTLANDS] =60
EKALLIANCETWO[HILLSBRAD] =60
EKALLIANCETWO[BURNINGSTEPPES] =59
EKALLIANCETWO[BLASTEDLANDS] =58
EKALLIANCETWO[SILVERPINE] =57
EKALLIANCETWO[BADLANDS] =58
EKALLIANCETWO[DUNMOROGH] =60

--needs to be in broadly level order.  split in 2
KALIMDORALLIANCEACHIEVEMENTS = {}
KALIMDORALLIANCEACHIEVEMENTS[ZONEQUESTS[DARKSHORE]] = 10
KALIMDORALLIANCEACHIEVEMENTS[ZONEQUESTS[BLOODMYST]] = 10
KALIMDORALLIANCEACHIEVEMENTS[DARKSHORE] = 15
KALIMDORALLIANCEACHIEVEMENTS[GHOSTSINTHEDARK] = 15
KALIMDORALLIANCEACHIEVEMENTS[BLOODMYST] = 15
KALIMDORALLIANCEACHIEVEMENTS[STONETALONALLY] = 30
KALIMDORALLIANCEACHIEVEMENTS[ASHENVALEALLY] = 20
KALIMDORALLIANCEACHIEVEMENTS[STONETALONQUESTSALLY] = 30
KALIMDORALLIANCEACHIEVEMENTS[ZONEQUESTS[ASHENVALEALLY]] = 20

KALIMDORALLIANCETWO = {}
KALIMDORALLIANCETWO[ZONEQUESTS[DESOLACE]] =35
KALIMDORALLIANCETWO[SOUTHERNBARRENSQUESTSA] =35
KALIMDORALLIANCETWO[FERALASQUESTSA] =40
KALIMDORALLIANCETWO[DUSTWALLOWMARSHQUESTSA] =40
KALIMDORALLIANCETWO[ZONEQUESTS[THOUSANDNEEDLES]] =40

EKHORDEACHIEVEMENTS = {}
EKHORDEACHIEVEMENTS[ZONEQUESTS[GHOSTLANDS]] = 10
EKHORDEACHIEVEMENTS[ZONEQUESTS[SILVERPINE]] = 10
EKHORDEACHIEVEMENTS[GHOSTLANDS] = 15
EKHORDEACHIEVEMENTS[SILVERPINE] = 15
EKHORDEACHIEVEMENTS[ZONEQUESTS[HILLSBRAD]] = 20
EKHORDEACHIEVEMENTS[HILLSBRAD] = 20
EKHORDEACHIEVEMENTS[ARATHI] =35
EKHORDEACHIEVEMENTS[ZONEQUESTS[ARATHI]] =35
EKHORDEACHIEVEMENTS[NORTHERNSTRANGLETHORN] =35
EKHORDEACHIEVEMENTS[ZONEQUESTS[NORTHERNSTRANGLETHORN]] =35
EKHORDEACHIEVEMENTS[GREENHILLS] =35
EKHORDEACHIEVEMENTS[CAPEOFSTRANGLETHORN] =40
EKHORDEACHIEVEMENTS[ZONEQUESTS[CAPEOFSTRANGLETHORN]] =40
EKHORDEACHIEVEMENTS[HINTERLANDS] =40
EKHORDEACHIEVEMENTS[ZONEQUESTS[HINTERLANDS]] =40
EKHORDEACHIEVEMENTS[EASTERNPLAGUELANDS] =40
EKHORDEACHIEVEMENTS[ZONEQUESTS[EASTERNPLAGUELANDS]] =40
EKHORDEACHIEVEMENTS[WESTERNPLAGUELANDS] =40
EKHORDEACHIEVEMENTS[ZONEQUESTS[WESTERNPLAGUELANDS]] =40
EKHORDEACHIEVEMENTS[FULLCARAVAN] =40
EKHORDEACHIEVEMENTS[ELWYNN] =60

AZSHARAACHS = {}
AZSHARAACHS[GLUTTONFIERY] = 15
AZSHARAACHS[GLUTTONICY] = 15
AZSHARAACHS[GLUTTONSHADOWY] = 15

DALARANACHS = {}
DALARANACHS[OURDAILYBREADA] = 1; --ALIANCE
DALARANACHS[OURDAILYBREADH] = 1; 
DALARANACHS[THERESGOLDINTHATTHEREFOUNTAIN]=70
DALARANACHS[SILVERINTHECITY]=70
DALARANACHS[THECOINMASTER]=70
DALARANACHS[APENNYFORYOURTHOUGHTS]=70
DALARANACHS[CHASINGMARCIA]=70
DALARANACHS[ISMELLAGIANTRAT]=70




STORMWINDCITYACHS = {}
STORMWINDCITYACHS[FISHORCUTBAITALLY] = 1
STORMWINDCITYACHS[COOKINGAWARD] = 1
STORMWINDCITYACHS[TENCOOKINGAWARDS] = 1
STORMWINDCITYACHS[LETSDOLUNCHALLY] = 1
STORMWINDCITYACHS[TWENTYFIVECOOKINGAWARDS] = 1
STORMWINDCITYACHS[FIFTYCOOKINGAWARDS] = 1
STORMWINDCITYACHS[HUNDREDCOOKINGAWARDS] = 1

KALIMDORHORDEACHIEVEMENTS = {}
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[NORTHERNBARRENS]] = 10
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[AZSHARA]] = 10
KALIMDORHORDEACHIEVEMENTS[JOYRIDE] = 10
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[ASHENVALEHORDE]] = 20
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[STONETALONHORDE]] = 30
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[THOUSANDNEEDLES]] =40
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[DESOLACE]] =35
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[SOUTHERNBARRENSH]] =35
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[FERALASH]] =40
KALIMDORHORDEACHIEVEMENTS[ZONEQUESTS[DUSTWALLOWMARSHH]] =40
KALIMDORHORDEACHIEVEMENTS[DARKSHORE] = 15
KALIMDORHORDEACHIEVEMENTS[BLOODMYST] = 15
KALIMDORHORDEACHIEVEMENTS[ASHENVALEHORDE] = 20
KALIMDORHORDEACHIEVEMENTS[STONETALONHORDE] = 30

KALIMDOREXPLOREACHIEVEMENTS = {}
KALIMDOREXPLOREACHIEVEMENTS[NORTHERNBARRENS] = 15
KALIMDOREXPLOREACHIEVEMENTS[AZSHARA] = 15
KALIMDOREXPLOREACHIEVEMENTS[THOUSANDNEEDLES] =40
KALIMDOREXPLOREACHIEVEMENTS[DESOLACE] =35
KALIMDOREXPLOREACHIEVEMENTS[SOUTHERNBARRENSH] =35
KALIMDOREXPLOREACHIEVEMENTS[FERALASH] =40
KALIMDOREXPLOREACHIEVEMENTS[DUSTWALLOWMARSHH] =40
KALIMDOREXPLOREACHIEVEMENTS[DESOLACE] =35
KALIMDOREXPLOREACHIEVEMENTS[SOUTHERNBARRENSA] =35
KALIMDOREXPLOREACHIEVEMENTS[FERALASA] =40
KALIMDOREXPLOREACHIEVEMENTS[DUSTWALLOWMARSHA] =40
KALIMDOREXPLOREACHIEVEMENTS[THOUSANDNEEDLES] =40
KALIMDOREXPLOREACHIEVEMENTS[WINTERSPRING]=60
KALIMDOREXPLOREACHIEVEMENTS[MULGORE]=60
KALIMDOREXPLOREACHIEVEMENTS[AZSHARA]=60
KALIMDOREXPLOREACHIEVEMENTS[FELWOOD]=60
KALIMDOREXPLOREACHIEVEMENTS[AZUREMYST]=59
KALIMDOREXPLOREACHIEVEMENTS[SILITHUS]=60
KALIMDOREXPLOREACHIEVEMENTS[DUROTAR]=60
KALIMDOREXPLOREACHIEVEMENTS[TANARIS]=59
KALIMDOREXPLOREACHIEVEMENTS[UNGOROCRATER]=58
KALIMDOREXPLOREACHIEVEMENTS[NORTHERNBARRENS]=60
KALIMDOREXPLOREACHIEVEMENTS[TELDRASSIL]=60
KALIMDOREXPLOREACHIEVEMENTS[MOONGLADE]=58

KALIMDORNEUTRALACHIEVEMENTS = {}
KALIMDORNEUTRALACHIEVEMENTS [SILITHUSQUESTS] = 30
KALIMDORNEUTRALACHIEVEMENTS [ZONEQUESTS[THOUSANDNEEDLES]]= 30
KALIMDORNEUTRALACHIEVEMENTS [FELWOODQUESTS]= 30
KALIMDORNEUTRALACHIEVEMENTS [TANARISQUESTS]= 30
KALIMDORNEUTRALACHIEVEMENTS [UNGOROCRATERQUESTS]= 30
KALIMDORNEUTRALACHIEVEMENTS [WINTERSPRINGQUESTS]= 30
KALIMDORNEUTRALACHIEVEMENTS [EKOMADNESS]= 30
KALIMDORNEUTRALACHIEVEMENTS [LOREMASTEROFKALIMDOR] = 40

EKNEUTRALACHIEVEMENTS = {}
EKNEUTRALACHIEVEMENTS[BADLANDSQUESTS] = 30
EKNEUTRALACHIEVEMENTS[BLASTEDLANDSQUESTS] = 40
EKNEUTRALACHIEVEMENTS[BURNINGSTEPPESQUESTS] = 40
EKNEUTRALACHIEVEMENTS[SEARINGGORGEQUESTS] = 30
EKNEUTRALACHIEVEMENTS[SWAMPOFSORROWSQUESTS] = 40
EKNEUTRALACHIEVEMENTS[READYSETGOAT] = 30
EKNEUTRALACHIEVEMENTS[LOREMASTEROFEASTERNKINGDOMS] = 40



--archaeology
ARAKKOAARCHIVIST=9412
ARTISANARCHAEOLOGIST=4920
BLUESTREAK=5193
DIGGER=5315
DIGGERER=5469
DIGGEREST=5470
DOCUMENTSOFADARKHISTORY=7337
DRAENORARCHAEOLOGIST=9409
DRAENORCURATOR=9419
EXPERTARCHAEOLOGIST=4919
GRANDMASTERARCHAEOLOGIST=4922
HIGHMAULHISTORIAN=9411
HISTORYOFTHEMANTID=8219
IHADITINMYHAND=4854
ILLUSTRIOUSGRANDMASTERARCHAEOLOGIST=4923
INSTRUMENTSOFCRUELTY=7334
ITBELONDSINAMUSEUM=4856
ITSALWAYSINTHELASTPLACEYOULOOK=5511
JOURNEYMANARCHAELOGIST=4857
KINGSUNDERTHEMOUNTAIN=4859
MASTERARCHAEOLOGIST=4921
OGREOBSERVER=9414
SECRETSOFSKETTIS=9415
SEVENSCEPTERS=4858
STONESERVANTS=7336
STRENGTHANDHONOR=9413
SYMBOLSOFSTRENGTH=7335
BOYWHOWOULDBEKING=5301
BROKENHEARTED=7332
FOURCELESTIALS=7333
HARDERTHEYFALL=5192
SEARCHFORFACTNOTTRUTH=9422
SEATOFKNOWLEDGE=7612
THREEBREWFATHERS=7331
TRAGEDYINTHREEACTS=5191
UNITETHECLANS=9410
WHATWASBRIEFLYYOURSISNOWMINE=4855
ZENMASTERARCHAEOLOGIST=6837

--collecvtor
COLLECTORANCIENTSAPFEEDERSFIVE=8223
COLLECTORANCIENTSAPFEEDERSTWENTY=8222
COLLECTORAPOTHECARYTINSFIVE=7345
COLLECTORAPOTHECARYTINSTWENTY=7365
COLLECTORBANNERSOFTHEMANTIDEMPIRETWENTY=8221
COLLECTORBANNERSOFTHEMANTIDEMPIREFIVE=8220
COLLECTORCARVEDBRONZEMIRRORSFIVE=7343
COLLECTORCARVEDBRONZEMIRRORSTWENTY=7363
COLLECTORCRACKEDMOGURUNESTONESTWENTY=7369
COLLECTORCRACKEDMOGURUNESTONESFIVE=7349
COLLECTOREDICTSOFTHETHUNDERKINGTWENTY=7373
COLLECTOREDICTSOFTHETHUNDERKINGFIVE=7353
COLLECTOREMPTYKEGSOFBREWFATHERXINWOYINFIVE=7342
COLLECTOREMPTYKEGSOFBREWFATHERXINWOYINTWENTY=7362
COLLECTORGOLDINLAINDPORCELAINFIVE=7344
COLLECTORGOLDINLAIDPORCCELAINTWENTY=7364
COLLECTORINERTSOUNDBEACONSTWENTY=8227
COLLECTORINERTSOUNDBEACONSFIVE=8226
COLLECTORIRONAMULETSFIVE=7354
COLLECTORIRONAMULETSTWENTY=7374
COLLECTORKYPARISAPTWENTY=8235
COLLECTORKYPARISAPFIVE=8234
COLLECTORMANACLESOFREBELLIONTWENTY=7368
COLLECTORMANACLESOFREBELLIONFIVE=7348
COLLECTORMANTIDLAMPSFIVE=8230
COLLECTORMANTIDLAMPSTWENTY=8231
COLLECTORMOGUCOINSTWENTY=7376
COLLECTORMOGUCOINSFIVE=7356
COLLECTORPANDARENGAMEBOARDSFIVE=7339
COLLECTORPANDARENGAMEBOARDSTWENTY=7359




ARCHAEOLOGYACHS = {}
ARCHAEOLOGYACHS[ARAKKOAARCHIVIST] = 20
ARCHAEOLOGYACHS[ARTISANARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[BLUESTREAK] = 20
ARCHAEOLOGYACHS[DIGGER] = 20
ARCHAEOLOGYACHS[DIGGERER] = 20
ARCHAEOLOGYACHS[DIGGEREST] = 20
ARCHAEOLOGYACHS[DOCUMENTSOFADARKHISTORY] = 20
ARCHAEOLOGYACHS[DRAENORARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[DRAENORCURATOR] = 20
ARCHAEOLOGYACHS[EXPERTARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[GRANDMASTERARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[HIGHMAULHISTORIAN] = 20
ARCHAEOLOGYACHS[HISTORYOFTHEMANTID] = 60
ARCHAEOLOGYACHS[IHADITINMYHAND] = 20
ARCHAEOLOGYACHS[ILLUSTRIOUSGRANDMASTERARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[INSTRUMENTSOFCRUELTY] = 20
ARCHAEOLOGYACHS[ITBELONDSINAMUSEUM] = 20
ARCHAEOLOGYACHS[ITSALWAYSINTHELASTPLACEYOULOOK] = 20
ARCHAEOLOGYACHS[JOURNEYMANARCHAELOGIST] = 20
ARCHAEOLOGYACHS[KINGSUNDERTHEMOUNTAIN] = 20
ARCHAEOLOGYACHS[MASTERARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[OGREOBSERVER] = 20
ARCHAEOLOGYACHS[SECRETSOFSKETTIS] = 20
ARCHAEOLOGYACHS[SEVENSCEPTERS] = 20
ARCHAEOLOGYACHS[STONESERVANTS] = 20
ARCHAEOLOGYACHS[STRENGTHANDHONOR] = 20
ARCHAEOLOGYACHS[SYMBOLSOFSTRENGTH] = 20
ARCHAEOLOGYACHS[BOYWHOWOULDBEKING] = 20
ARCHAEOLOGYACHS[BROKENHEARTED] = 20
ARCHAEOLOGYACHS[FOURCELESTIALS] = 20
ARCHAEOLOGYACHS[HARDERTHEYFALL] = 20
ARCHAEOLOGYACHS[SEARCHFORFACTNOTTRUTH] = 20
ARCHAEOLOGYACHS[SEATOFKNOWLEDGE] = 20
ARCHAEOLOGYACHS[THREEBREWFATHERS] = 20
ARCHAEOLOGYACHS[TRAGEDYINTHREEACTS] = 20
ARCHAEOLOGYACHS[UNITETHECLANS] = 20
ARCHAEOLOGYACHS[WHATWASBRIEFLYYOURSISNOWMINE] = 20
ARCHAEOLOGYACHS[ZENMASTERARCHAEOLOGIST] = 20
ARCHAEOLOGYACHS[COLLECTORANCIENTSAPFEEDERSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORANCIENTSAPFEEDERSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORAPOTHECARYTINSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORAPOTHECARYTINSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORBANNERSOFTHEMANTIDEMPIRETWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORBANNERSOFTHEMANTIDEMPIREFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORCARVEDBRONZEMIRRORSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORCARVEDBRONZEMIRRORSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORCRACKEDMOGURUNESTONESTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORCRACKEDMOGURUNESTONESFIVE] = 85
ARCHAEOLOGYACHS[COLLECTOREDICTSOFTHETHUNDERKINGTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTOREDICTSOFTHETHUNDERKINGFIVE] = 85
ARCHAEOLOGYACHS[COLLECTOREMPTYKEGSOFBREWFATHERXINWOYINFIVE] = 85
ARCHAEOLOGYACHS[COLLECTOREMPTYKEGSOFBREWFATHERXINWOYINTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORGOLDINLAINDPORCELAINFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORGOLDINLAIDPORCCELAINTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORINERTSOUNDBEACONSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORINERTSOUNDBEACONSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORIRONAMULETSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORIRONAMULETSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORKYPARISAPTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORKYPARISAPFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORMANACLESOFREBELLIONTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORMANACLESOFREBELLIONFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORMANTIDLAMPSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORMANTIDLAMPSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORMOGUCOINSTWENTY] = 85
ARCHAEOLOGYACHS[COLLECTORMOGUCOINSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORPANDARENGAMEBOARDSFIVE] = 85
ARCHAEOLOGYACHS[COLLECTORPANDARENGAMEBOARDSTWENTY] = 85


--toys

OUTLANDANGLER=1225
MRPINCHYSMAGICALCRAWDADBOX=726
OLDMANBARLOWNED=905
FISHDONTLEAVEFOOTPRINTS=1243
OLDCRAFTY=1836
OLDIRONJAW=1837
FISHINGDIPLOMAT=150
SEASCORPIONANGLER=9461
BLINDLAKESTURGEONANGLER=9458
BLACKWATERWHIPTAILANGLER=9457

FISHINGACHS = {}
FISHINGACHS[OLDGNOMEANDTHESEA]=30
FISHINGACHS[LIMNOLOGIST]=70
FISHINGACHS[OCEANOGRAPHER]=70
FISHINGACHS[OUTLANDANGLER] = 60
FISHINGACHS[MRPINCHYSMAGICALCRAWDADBOX] = 60
FISHINGACHS[OLDMANBARLOWNED] = 60
FISHINGACHS[FISHDONTLEAVEFOOTPRINTS] = 5
FISHINGACHS[OLDCRAFTY] = 5
FISHINGACHS[OLDIRONJAW] = 5
FISHINGACHS[FISHINGDIPLOMAT] = 5
FISHINGACHS[SEASCORPIONANGLER] = 90
FISHINGACHS[BLINDLAKESTURGEONANGLER] = 90
FISHINGACHS[BLACKWATERWHIPTAILANGLER] = 90






--proving grounds, no max level so dont treat as dungeon?

PROVINGYOURSELFBRONZEDAMAGE=9572
PROVINGYOURSELFBRONZEHEALER=9584
PROVINGYOURSELFBRONZETANK=9578
PROVINGYOURSELFSILVERDAMAGE=9573
PROVINGYOURSELFSILVERHEALER=9585
PROVINGYOURSELFSILVERTANK=9579
PROVINGYOURSELFGOLDDAMAGE=9574
PROVINGYOURSELFGOLDHEALER=9586
PROVINGYOURSELFGOLDTANK=9580
PROVINGYOURSELFENDLESSDAMAGETEN=9575
PROVINGYOURSELFENDLESSEHEALERTEN=9587
PROVINGYOURSELFENDLESSTANKTEN=9581
PROVINGYOURSELFENDLESSDAMAGETWENTY=9576
PROVINGYOURSELFENDLESSEHEALERTWENTY=9588
PROVINGYOURSELFENDLESSTANKTWENTY=9582
PROVINGYOURSELFENDLESSDAMAGETHIRTY=9577
PROVINGYOURSELFENDLESSEHEALERTHIRTY=9589
PROVINGYOURSELFENDLESSTANKTHIRTY=9583
YOUREDOINGITWRONG=9590

PROVINGGROUNDSTANK = {}
PROVINGGROUNDSTANK [PROVINGYOURSELFBRONZETANK] = 95
PROVINGGROUNDSTANK [PROVINGYOURSELFSILVERTANK] = 95
PROVINGGROUNDSTANK [PROVINGYOURSELFGOLDTANK] = 95
PROVINGGROUNDSTANK [PROVINGYOURSELFENDLESSTANKTEN] = 95
PROVINGGROUNDSTANK [PROVINGYOURSELFENDLESSTANKTWENTY] = 95
PROVINGGROUNDSTANK [PROVINGYOURSELFENDLESSTANKTHIRTY] = 95

PROVINGGROUNDSHEAL = {}
PROVINGGROUNDSHEAL [PROVINGYOURSELFBRONZEHEALER] = 95
PROVINGGROUNDSHEAL [PROVINGYOURSELFSILVERHEALER] = 95
PROVINGGROUNDSHEAL [PROVINGYOURSELFGOLDHEALER] = 95
PROVINGGROUNDSHEAL [PROVINGYOURSELFENDLESSEHEALERTEN] = 95
PROVINGGROUNDSHEAL [PROVINGYOURSELFENDLESSEHEALERTWENTY] = 95
PROVINGGROUNDSHEAL [PROVINGYOURSELFENDLESSEHEALERTHIRTY] = 95


PROVINGGROUNDSACHS = {}
PROVINGGROUNDSACHS [PROVINGYOURSELFBRONZEDAMAGE] = 95
PROVINGGROUNDSACHS [PROVINGYOURSELFSILVERDAMAGE] = 95
PROVINGGROUNDSACHS [PROVINGYOURSELFGOLDDAMAGE] = 95
PROVINGGROUNDSACHS [PROVINGYOURSELFENDLESSDAMAGETEN] = 95
PROVINGGROUNDSACHS [PROVINGYOURSELFENDLESSDAMAGETWENTY] = 95
PROVINGGROUNDSACHS [PROVINGYOURSELFENDLESSDAMAGETHIRTY] = 95
PROVINGGROUNDSACHS [YOUREDOINGITWRONG] = 95

--mounts
LEADINGTHECAVALRY=2143
AWAKETHEDRAKES=9713
MOUNTAINOMOUNTS=2537
--most of these dont worry about until close
MOUNTACHS = {}
MOUNTACHS[LEADINGTHECAVALRY] = 90
MOUNTACHS[AWAKETHEDRAKES] = 90
MOUNTACHS[MOUNTAINOMOUNTS] = 90

