
ANDTHEMEEKSHALLINHERIT=5868
BEWAREOFTHEUNBEATABLE=4959
BOUNCE=5483
BREAKINGOUTOFTOLBARAD=4874
COMINGDOWNTHEMOUNTAIN=4870
CONSUMEDBYNIGHTMARE=5451
DEATHFROMABOVE=5874
DEEPINTODEEPHOLM=4871
FIRESIDECHAT=5870
FLAWLESSVICTORY=5867
FUNGALFRENZY=5450
FUNGALOPHOBIA=5445
GANGWAR=5864
HAVEHAVEWEMET=5865
HELPTHEBOMBARDIER=5317
INATHOUSANDYEARS=4961
INFERNALAMBASSADORS=5869
KINGOFTHESPIDERHILL=5872
LEGACYOFLEYARA=5859
LOREMASTEROFCATACLYSM=4875
LUDICROUSSPEED=5862
MASTEROFTHEMOLTENFLOW=5871
MYVERYOWNBROODMOTHER=5447
READYFORRAIDINGII=5873
ROCKLOVER=5449
ROUNDTHREEFIGHT=4960
THEUNBEATABLEBEATEN=5860
FIERYLORDSOFSETHRIA=5861
GLOPFAMILYLINE=5446
MOLTENFRONTOFFENSIVE=5866
UNEARTHINGULDUM=4872
VETERANOFMOLTENFRONT=5879
VISIONSOFVASHIJRPAST=5452




--cata
COMINGDOWNTHEMOUNTAIN = 4870
UNBEATABLE = 4959
BEATEN = 5860
BOUNCE =5483


EXPLOREULDUM=4865
EXPLOREVASHJIR=4825
EXPLOREHYJAL=4863
EXPLOREDEEPHOLM=4864
EXPLORETWILIGHTHIGHLANDS=4866
SURVEYINGTHEDAMAGE=4827
FROMHELLSHEARTISTABATTHEE=4975
STOODINTHEFIRE=5518

--rep
AVENGERSOFHYJAL=5827
RAMKAHEN=4884
EARTHENRING=4881
GUARDIANSOFHYJAL=4882
THERAZANE=4883
--need to add ally and horde specific
BARADINSWARDENS=5375
WILDHAMMERCLAN=4885
DRAGONMAWCLAN=4886
HELLSCREAMSREACH=5376

CATACLYSMACHS = {}
CATACLYSMACHS[EXPLOREULDUM] = 83
CATACLYSMACHS[EXPLOREVASHJIR] = 80
CATACLYSMACHS[EXPLOREHYJAL] = 80
CATACLYSMACHS[EXPLOREDEEPHOLM] = 83
CATACLYSMACHS[EXPLORETWILIGHTHIGHLANDS] = 83
CATACLYSMACHS[SURVEYINGTHEDAMAGE] = 80
CATACLYSMACHS[FROMHELLSHEARTISTABATTHEE] = 80
CATACLYSMACHS[STOODINTHEFIRE] = 80
CATACLYSMACHS[AVENGERSOFHYJAL] = 80
CATACLYSMACHS[RAMKAHEN] = 80
CATACLYSMACHS[EARTHENRING] = 80
CATACLYSMACHS[GUARDIANSOFHYJAL] = 80
CATACLYSMACHS[THERAZANE] = 80


CATAQUESTS = {}
CATAQUESTS[ANDTHEMEEKSHALLINHERIT] = 85
CATAQUESTS[BEWAREOFTHEUNBEATABLE] = 80
CATAQUESTS[BOUNCE] = 80
CATAQUESTS[BREAKINGOUTOFTOLBARAD] = 85
CATAQUESTS[COMINGDOWNTHEMOUNTAIN] = 80
CATAQUESTS[CONSUMEDBYNIGHTMARE] = 85
CATAQUESTS[DEATHFROMABOVE] = 85
CATAQUESTS[DEEPINTODEEPHOLM] = 83
CATAQUESTS[FIRESIDECHAT] = 85
CATAQUESTS[FLAWLESSVICTORY] = 85
CATAQUESTS[FUNGALFRENZY] = 83
CATAQUESTS[FUNGALOPHOBIA] = 83
CATAQUESTS[GANGWAR] = 85
CATAQUESTS[HAVEHAVEWEMET] = 85
CATAQUESTS[HELPTHEBOMBARDIER] = 80
CATAQUESTS[INATHOUSANDYEARS] = 80
CATAQUESTS[INFERNALAMBASSADORS] = 85
CATAQUESTS[KINGOFTHESPIDERHILL] = 85
CATAQUESTS[LEGACYOFLEYARA] = 85
CATAQUESTS[LOREMASTEROFCATACLYSM] = 85
CATAQUESTS[LUDICROUSSPEED] = 85
CATAQUESTS[MASTEROFTHEMOLTENFLOW] = 85
CATAQUESTS[MYVERYOWNBROODMOTHER] = 83
CATAQUESTS[READYFORRAIDINGII] = 85
CATAQUESTS[ROCKLOVER] = 83
CATAQUESTS[ROUNDTHREEFIGHT] = 85
CATAQUESTS[THEUNBEATABLEBEATEN] = 85
CATAQUESTS[FIERYLORDSOFSETHRIA] = 85
CATAQUESTS[GLOPFAMILYLINE] = 83
CATAQUESTS[MOLTENFRONTOFFENSIVE] = 85
CATAQUESTS[UNEARTHINGULDUM] = 80
CATAQUESTS[VETERANOFMOLTENFRONT] = 85
CATAQUESTS[VISIONSOFVASHIJRPAST] = 80

TWENTYTHOUSANDLEAGUESA=5318
FADINGINTOTWILIGHTA=4873
KINGOFTHEMOUNTAINA=5320
SINKINGINTOVASHJIRA=4869
WILDHAMMERTOUROFDUTY=5481


TWENTYTHOUSANDLEAGUESH=5319
FADINGINTOTWILIGHTH=5501
KINGOFTHEMOUNTAINH=5321
SINKINGINTOVASHJIRH=4982
DRAGONMAWTOUROFDUTY=5482

CATAQUESTSALLY  = {}
CATAQUESTSALLY[TWENTYTHOUSANDLEAGUESA] = 80
CATAQUESTSALLY[FADINGINTOTWILIGHTA] = 83
CATAQUESTSALLY[KINGOFTHEMOUNTAINA] = 85
CATAQUESTSALLY[SINKINGINTOVASHJIRA] = 80
CATAQUESTSALLY[WILDHAMMERTOUROFDUTY] = 85
CATAQUESTSALLY[BARADINSWARDENS] = 85
CATAQUESTSALLY[WILDHAMMERCLAN] = 85


CATAQUESTSHORDE  = {}
CATAQUESTSHORDE[TWENTYTHOUSANDLEAGUESH] = 80
CATAQUESTSHORDE[FADINGINTOTWILIGHTH] = 83
CATAQUESTSHORDE[KINGOFTHEMOUNTAINH] = 85
CATAQUESTSHORDE[SINKINGINTOVASHJIRH] = 80
CATAQUESTSHORDE[DRAGONMAWTOUROFDUTY] = 85
CATAQUESTSHORDE[DRAGONMAWCLAN] = 85
CATAQUESTSHORDE[HELLSCREAMSREACH] = 85


