SPIRESOFARAK = "Spires of Arak"
SHADOWMOONVALLEY = "Shadowmoon Valley"
EVERBLOOMWILDS = "Everbloom Wilds"

EXPLOREFROSTFIRERIDGE=8937
EXPLOREGORGROND=8939
EXPLORENAGRAND=8942
EXPLORESHADOWMOONVALLEY=8938
EXPLORESPIRESOFARAK=8941
EXPLORETALADOR=8940
EXPLOREDRAENOR=8935
FIELDPHOTOGRAPHER=9924
GORGRONDMONSTERHUNTER=9400
GRANDTREASUREHUNTER=9728
MASTERTREASUREHUNTER=9727 --now expert treasure hunter?
PROVEYOURSTRENGTH=9402
SHREDDERMANIAC=9401
TREASUREHUNTER=9726
DRAENORPATHFINDER=10018
JUNGLETREASUREHUNTER=10261
JUNGLETREASUREMASTER=10262
JUNGLEHUNTER=10259
JUNGLESTALKER=10070
EXPLORETANAANJUNGLE=10260
HELLBANE = 10061
ICAMEICLAWEDICONQUERED = 10069
WORLDEXPLORER=46

DRAENOREXPLOREACHS = {}

DRAENOREXPLOREACHS[EXPLOREFROSTFIRERIDGE] = 95
DRAENOREXPLOREACHS[EXPLOREGORGROND] = 95
DRAENOREXPLOREACHS[EXPLORENAGRAND] = 95
DRAENOREXPLOREACHS[EXPLORESHADOWMOONVALLEY] = 90
DRAENOREXPLOREACHS[EXPLORESPIRESOFARAK] = 95
DRAENOREXPLOREACHS[EXPLORETALADOR] = 95
DRAENOREXPLOREACHS[GRANDTREASUREHUNTER] = 95
DRAENOREXPLOREACHS[MASTERTREASUREHUNTER] = 95
DRAENOREXPLOREACHS[TREASUREHUNTER] = 90
DRAENOREXPLOREACHS[DRAENORPATHFINDER] = 98
DRAENOREXPLOREACHS[JUNGLETREASUREHUNTER] = 98
DRAENOREXPLOREACHS[JUNGLETREASUREMASTER] = 98
DRAENOREXPLOREACHS[JUNGLEHUNTER] = 98
DRAENOREXPLOREACHS[JUNGLESTALKER] = 98
DRAENOREXPLOREACHS[EXPLORETANAANJUNGLE] = 98
DRAENOREXPLOREACHS[ICAMEICLAWEDICONQUERED] = 98
DRAENOREXPLOREACHS[HELLBANE] = 98
DRAENOREXPLOREACHS[EXPLOREDRAENOR] = 100
DRAENOREXPLOREACHS[FIELDPHOTOGRAPHER] = 100
DRAENOREXPLOREACHS[WORLDEXPLORER] = 100

ADEMIDOSOFREALITY=9437
AVOIDANCE=9433
ANCIENTNOMORE=9678
ARAKSTAR=9605
BOBBINGFORORCS=9635
BREAKEROFCHAINS=9533
BROKEBACKPRECIPICE=9571
BURIEDTREASURES=9548
BURNITTOTHEGROUND=9667
BYFIREBEMERGED=9537
CHARGEDUP=9634
CUTOFFTHEHEAD=9633
DELECTABLEORGREDELICACIES=9534
EGGSINONEBASKET=9612
FIGHTTHEPOWER=9655
FISHGOTTASWIMBIRDSGOTTAEAT=9613

GORGRONDACHS = {}
GORGRONDACHS[GORGRONDMONSTERHUNTER] = 93
GORGRONDACHS[SHREDDERMANIAC] = 93
GORGRONDACHS[PROVEYOURSTRENGTH] = 93


DRAENORQUESTACHS = {}
DRAENORQUESTACHS[ADEMIDOSOFREALITY]=93
DRAENORQUESTACHS[AVOIDANCE]=93
DRAENORQUESTACHS[ANCIENTNOMORE]=93
DRAENORQUESTACHS[BOBBINGFORORCS]=93
DRAENORQUESTACHS[BREAKEROFCHAINS]=93
DRAENORQUESTACHS[BROKEBACKPRECIPICE]=93
DRAENORQUESTACHS[BURIEDTREASURES]=93
DRAENORQUESTACHS[BYFIREBEMERGED]=93
DRAENORQUESTACHS[CHARGEDUP]=93
DRAENORQUESTACHS[CUTOFFTHEHEAD]=94
DRAENORQUESTACHS[DELECTABLEORGREDELICACIES]=93
DRAENORQUESTACHS[EGGSINONEBASKET]=94
DRAENORQUESTACHS[FIGHTTHEPOWER]=94
DRAENORQUESTACHS[FISHGOTTASWIMBIRDSGOTTAEAT]=93

--ALLY

SHADOWMOONVALLEYACHS = {}
SHADOWMOONVALLEYACHS[EXPLORESHADOWMOONVALLEY] = 90

SPIRESOFARAKACHS = {}
SPIRESOFARAKACHS[ARAKSTAR] = 90

EVERBLOOMWILDSACHS = {}
EVERBLOOMWILDSACHS[BURNITTOTHEGROUND] = 90
--EVERBLOOMWILDSACHS[MEANANDGREEN] = 90
--EVERBLOOMWILDSACHS[PICKYPALATE] = 90
--EVERBLOOMWILDSACHS[PILLARSOFDRAENOR] = 90

ASIWALKTHROUGHTHEVALLEY=8845
BETWEENARAKANDAHARDPLACEA=8925
DONTLETTHETALADOORHITYOUA=8920
NAGRANDEURA=8927
ONTHESHADOWSTRAILA=9528
PUTTINGTHEGOREINGORGRONDA=8923
SECURINGDRAENORA=9564
SHOOTFORTHEMOON=9602
GARRISONCAMPAIGNA=9491
WELCOMETODRAENORA=8921
WRITINGINTHESNOWA=9530

DRAENORALLYQUESTACHS = {}

DRAENORALLYQUESTACHS [ASIWALKTHROUGHTHEVALLEY] = 90
DRAENORALLYQUESTACHS [BETWEENARAKANDAHARDPLACEA] = 93
DRAENORALLYQUESTACHS [DONTLETTHETALADOORHITYOUA] = 93
DRAENORALLYQUESTACHS [NAGRANDEURA] = 95
DRAENORALLYQUESTACHS [ONTHESHADOWSTRAILA] = 90
DRAENORALLYQUESTACHS [PUTTINGTHEGOREINGORGRONDA] = 93
DRAENORALLYQUESTACHS [SECURINGDRAENORA] = 95
DRAENORALLYQUESTACHS [SHOOTFORTHEMOON] = 90
DRAENORALLYQUESTACHS [GARRISONCAMPAIGNA] = 95
DRAENORALLYQUESTACHS [WELCOMETODRAENORA] = 90
DRAENORALLYQUESTACHS [WRITINGINTHESNOWA] = 93

--HORDE

BETWEENARAKANDAHARDPLACEH=8926
DONTLETTHETALADOORHITYOUH=8919
FROSTFIREFRIDGE=9606
NAGRANDEURH=8928
ONTHESHADOWSTRAILH=9529
PUTTINGTHEGOREINGORGRONDH=8924
SECURINGDRAENORH=9562
GARRISONCAMPAIGNH=9492
WELCOMETODRAENORH=8922
WRITINGINTHESNOWH=9531
YOULLGETCAUGHTUPINTHEFROSTFIRE=8671


DRAENORHORDEQUESTACHS = {}
DRAENORHORDEQUESTACHS [BETWEENARAKANDAHARDPLACEH] = 90
DRAENORHORDEQUESTACHS [DONTLETTHETALADOORHITYOUH] = 90
DRAENORHORDEQUESTACHS [FROSTFIREFRIDGE] = 90
DRAENORHORDEQUESTACHS [NAGRANDEURH] = 90
DRAENORHORDEQUESTACHS [ONTHESHADOWSTRAILH] = 90
DRAENORHORDEQUESTACHS [PUTTINGTHEGOREINGORGRONDH] = 90
DRAENORHORDEQUESTACHS [SECURINGDRAENORH] = 90
DRAENORHORDEQUESTACHS [GARRISONCAMPAIGNH] = 90
DRAENORHORDEQUESTACHS [WELCOMETODRAENORH] = 90
DRAENORHORDEQUESTACHS [WRITINGINTHESNOWH] = 90
DRAENORHORDEQUESTACHS [YOULLGETCAUGHTUPINTHEFROSTFIRE] = 90

--neutral
STAYINGREGULAR=8933
BOTANIINVASION=9208
BRONZEDEFENDER=9162
GOLDENDEFENDER=9165
GORENINVASION=9207
IMPERVIOUSDEFENDER=9827
INVASIONSPECIALIST=9167
INVASIONWHATINVASION=9543
INVASIONSAREBETTERWITHFRIENDS=9244
IRONHORDEINVASION=9205
ITSANINVASION=9152
MASTERANDCOMMANDER=9858
MASTERDEFENDER=9209
OGREINVASION=9204
PLATINUMDEFENDER=9826
SAVETHOSEBUILDINGS=9181
SHADOWCOUNCILINVASION=9203
SHADOWMOONCLANINVASION=9206
SILVERDEFENDER=9164
DRAENORPETBRAWLER=9264
MASTERDRAENORCRAFTER=9246
MASTEROFAPEXIS=9265
ARAREMISSION=9141
EXPLORATIONMISSIONMASTER=9900
EXPLORATIONMISSIONSPECIALIST=9150
KEEPINGITRARE=9142
MISSIONSPECIALIST=9147
ONAFEWMISSIONS=9134
ONALOTOFMISSIONS=9138
ONAMASSIVENUMBEROFMISSIONS=9139
ONAMETRICTONOFMISSIONS=9140
ONAMISSION=9133
PATROLMISSIONSPECIALIST=9146
PATROLLINGDRAENOR=9523
THERARERTHEBETTER=9143
TREASUREMASTER=9524
TREASUREMISSIONSPECIALIST=9145



--alliance
AZEROTHSTOPTWENTYTUNESA=9912
DONTCALLMEJUNIORA=9928
EVENMOREPLOTSA=9101
FULLDISCOGRAPHYA=10015
GARRISONBUDDIESA=9210
MOREPLOTSA=9100
TENHITTUNESA=9828
DEFENDEROFDRAENORA=9630
MYTHICDRAENORRAIDERA=9631

--horde
AZEROTHSTOPTWENTYTUNESH=9914
DONTCALLMEJUNIORH=9901
EVENMOREPLOTSH=9546
FULLDISCOGRAPHYH=10016
GARRISONBUDDIESH=9132
MOREPLOTSH=9545
TENHITTUNESH=9897
DEFENDEROFDRAENORH=9248
MYTHICDRAENORRAIDERH=9255


--neutral
DRAENORGARRISONACHS = {}
DRAENORGARRISONACHS [STAYINGREGULAR] = 85
DRAENORGARRISONACHS [BOTANIINVASION] = 85
DRAENORGARRISONACHS [BRONZEDEFENDER] = 85
DRAENORGARRISONACHS [GOLDENDEFENDER] = 85
DRAENORGARRISONACHS [GORENINVASION] = 85
DRAENORGARRISONACHS [IMPERVIOUSDEFENDER] = 85
DRAENORGARRISONACHS [INVASIONSPECIALIST] = 85
DRAENORGARRISONACHS [INVASIONWHATINVASION] = 85
DRAENORGARRISONACHS [INVASIONSAREBETTERWITHFRIENDS] = 85
DRAENORGARRISONACHS [IRONHORDEINVASION] = 85
DRAENORGARRISONACHS [ITSANINVASION] = 85
DRAENORGARRISONACHS [MASTERANDCOMMANDER] = 85
DRAENORGARRISONACHS [MASTERDEFENDER] = 85
DRAENORGARRISONACHS [OGREINVASION] = 85
DRAENORGARRISONACHS [PLATINUMDEFENDER] = 85
DRAENORGARRISONACHS [SAVETHOSEBUILDINGS] = 85
DRAENORGARRISONACHS [SHADOWCOUNCILINVASION] = 85
DRAENORGARRISONACHS [SHADOWMOONCLANINVASION] = 85
DRAENORGARRISONACHS [SILVERDEFENDER] = 85
DRAENORGARRISONACHS [DRAENORPETBRAWLER] = 85
DRAENORGARRISONACHS [MASTERDRAENORCRAFTER] = 85
DRAENORGARRISONACHS [MASTEROFAPEXIS] = 90
DRAENORGARRISONACHS [ARAREMISSION] = 85
DRAENORGARRISONACHS [EXPLORATIONMISSIONMASTER] = 85
DRAENORGARRISONACHS [EXPLORATIONMISSIONSPECIALIST] = 85
DRAENORGARRISONACHS [KEEPINGITRARE] = 85
DRAENORGARRISONACHS [MISSIONSPECIALIST] = 85
DRAENORGARRISONACHS [ONAFEWMISSIONS] = 85
DRAENORGARRISONACHS [ONALOTOFMISSIONS] = 85
DRAENORGARRISONACHS [ONAMASSIVENUMBEROFMISSIONS] = 85
DRAENORGARRISONACHS [ONAMETRICTONOFMISSIONS] = 85
DRAENORGARRISONACHS [ONAMISSION] = 85
DRAENORGARRISONACHS [PATROLMISSIONSPECIALIST] = 85
DRAENORGARRISONACHS [PATROLLINGDRAENOR] = 85
DRAENORGARRISONACHS [THERARERTHEBETTER] = 85
DRAENORGARRISONACHS [TREASUREMASTER] = 85
DRAENORGARRISONACHS [TREASUREMISSIONSPECIALIST] = 85

--alliance
DRAENORALLYGARRISONACHS = {}
DRAENORALLYGARRISONACHS [AZEROTHSTOPTWENTYTUNESA] = 85
DRAENORALLYGARRISONACHS [DONTCALLMEJUNIORA] = 85
DRAENORALLYGARRISONACHS [EVENMOREPLOTSA] = 85
DRAENORALLYGARRISONACHS [FULLDISCOGRAPHYA] = 85
DRAENORALLYGARRISONACHS [GARRISONBUDDIESA] = 85
DRAENORALLYGARRISONACHS [MOREPLOTSA] = 85
DRAENORALLYGARRISONACHS [TENHITTUNESA] = 85
DRAENORALLYGARRISONACHS [DEFENDEROFDRAENORA] = 85
DRAENORALLYGARRISONACHS [MYTHICDRAENORRAIDERA] = 85


--horde
DRAENORHORDEGARRISONACHS = {}
DRAENORHORDEGARRISONACHS [AZEROTHSTOPTWENTYTUNESH] = 85
DRAENORHORDEGARRISONACHS [DONTCALLMEJUNIORH] = 85
DRAENORHORDEGARRISONACHS [EVENMOREPLOTSH] = 85
DRAENORHORDEGARRISONACHS [FULLDISCOGRAPHYH] = 85
DRAENORHORDEGARRISONACHS [GARRISONBUDDIESH] = 85
DRAENORHORDEGARRISONACHS [MOREPLOTSH] = 85
DRAENORHORDEGARRISONACHS [TENHITTUNESH] = 85
DRAENORHORDEGARRISONACHS [DEFENDEROFDRAENORH] = 85
DRAENORHORDEGARRISONACHS [MYTHICDRAENORRAIDERH] = 85

--rep

--ally rep
COUNCILOFEXARCHS=9470
SAVAGEFRIENDSA=9478
SHATARIDEFENSE=9476
TANAANDIPLOMATA=10350
WRYNNSVANGUARD=9474

--NEUTRAL REP
ARAKKOAOUTCASTS=9469
MANTLEOFTHETALONKING=9072
STEAMWHEEDLEPRESERVATIONSOCIETY=9472

--HORDE REP
FROSTWOLFORCS=9471
LAUGHINGSKULLORCS=9475
SAVAGEFRIENDSH=9477
TANANNDIPLOMATH=10349
VOLJINSSPEAR=9473

DRAENORALLYREPACHS = {}

--ally rep
DRAENORALLYREPACHS[COUNCILOFEXARCHS] = 90
DRAENORALLYREPACHS[SAVAGEFRIENDSA] = 90
DRAENORALLYREPACHS[SHATARIDEFENSE] = 90
DRAENORALLYREPACHS[TANAANDIPLOMATA] = 90
DRAENORALLYREPACHS[WRYNNSVANGUARD] = 90

DRAENORNEUTRALREPACHS = {}

--NEUTRAL REP
DRAENORNEUTRALREPACHS[ARAKKOAOUTCASTS] = 90
DRAENORNEUTRALREPACHS[MANTLEOFTHETALONKING] = 90
DRAENORNEUTRALREPACHS[STEAMWHEEDLEPRESERVATIONSOCIETY] = 90


DRAENORHORDEREPACHS = {}

--HORDE REP
DRAENORHORDEREPACHS[FROSTWOLFORCS] = 90
DRAENORHORDEREPACHS[LAUGHINGSKULLORCS] = 90
DRAENORHORDEREPACHS[SAVAGEFRIENDSH] = 90
DRAENORHORDEREPACHS[TANANNDIPLOMATH] = 90
DRAENORHORDEREPACHS[VOLJINSSPEAR] = 90

--BRAWLERSGUILD

BOTTLESERVICE=7944
HATERSGONNAHATE=7945
IMYOURNUMBERONEFAN=7943

BRAWLERSGUILDACHS = {}
BRAWLERSGUILDACHS[BOTTLESERVICE] = 90
BRAWLERSGUILDACHS[HATERSGONNAHATE] = 90
BRAWLERSGUILDACHS[IMYOURNUMBERONEFAN] = 90

--BG ALLIANCE
BRAWLINANDSHOTCALLINA=9170
COLLECTYOURDECKA=8339
DECKYOURCOLLECTIONA=9176
NOWYOUREJUSTSHOWINGOFFA=9171
RABBLERABBLERABBLEA=7949
FIRSTRULEOFBRAWLERSGUILDA=7947
SECONDRULEOFBRAWLERSGUILDA=9169
YOUARENOTYOURLEGPLATESA=9168

BRAWLERSALLYACHS = {}

BRAWLERSALLYACHS[BRAWLINANDSHOTCALLINA] = 90
BRAWLERSALLYACHS[COLLECTYOURDECKA] = 90
BRAWLERSALLYACHS[DECKYOURCOLLECTIONA] = 90
BRAWLERSALLYACHS[NOWYOUREJUSTSHOWINGOFFA] = 90
BRAWLERSALLYACHS[RABBLERABBLERABBLEA] = 90
BRAWLERSALLYACHS[FIRSTRULEOFBRAWLERSGUILDA] = 90
BRAWLERSALLYACHS[SECONDRULEOFBRAWLERSGUILDA] = 90
BRAWLERSALLYACHS[YOUARENOTYOURLEGPLATESA] = 90



--BG HORDE
BRAWLINANDSHOTCALLINH=9174
COLLECTYOURDECKH=8342
DECKYOURCOLLECTIONH=9177
NOWYOUREJUSTSHOWINGOFFH=9175
RABBLERABBLERABBLEH=7950
FIRSTRULEOFBRAWLERSGUILDH=7948
SECONDRULEOFBRAWLERSGUILDH=9173
YOUARENOTYOURLEGPLATESH=9172

BRAWLERSHORDEACHS = {}

BRAWLERSHORDEACHS[BRAWLINANDSHOTCALLINH] = 90
BRAWLERSHORDEACHS[COLLECTYOURDECKH] = 90
BRAWLERSHORDEACHS[DECKYOURCOLLECTIONH] = 90
BRAWLERSHORDEACHS[NOWYOUREJUSTSHOWINGOFFH] = 90
BRAWLERSHORDEACHS[RABBLERABBLERABBLEH] = 90
BRAWLERSHORDEACHS[FIRSTRULEOFBRAWLERSGUILDH] = 90
BRAWLERSHORDEACHS[SECONDRULEOFBRAWLERSGUILDH] = 90
BRAWLERSHORDEACHS[YOUARENOTYOURLEGPLATESH] = 90
