SPIRESOFARAK = "Spires of Arak"
SHADOWMOONVALLEY = "Shadowmoon Valley"
EVERBLOOMWILDS = "Everbloom Wilds"

EXPLOREFROSTFIRERIDGE=8937
EXPLOREGORGROND=8939
EXPLORENAGRAND=8942
EXPLORESHADOWMOONVALLEY=8938
EXPLORESPIRESOFARAK=8941
EXPLORETALADOR=8940
EXPLOREDRAENOR=8935
FIELDPHOTOGRAPHER=9924
GORGRONDMONSTERHUNTER=9400
GRANDTREASUREHUNTER=9728
MASTERTREASUREHUNTER=9727 --now expert treasure hunter?
PROVEYOURSTRENGTH=9402
SHREDDERMANIAC=9401
TREASUREHUNTER=9726
DRAENORPATHFINDER=10018
JUNGLETREASUREHUNTER=10261
JUNGLETREASUREMASTER=10262
JUNGLEHUNTER=10259
JUNGLESTALKER=10070
EXPLORETANAANJUNGLE=10260
HELLBANE = 10061
ICAMEICLAWEDICONQUERED = 10069
WORLDEXPLORER=46
WAKETHEDRAGON=11178
DRAENOREXPLOREACHS = {}

DRAENOREXPLOREACHS[EXPLOREFROSTFIRERIDGE] = 95
DRAENOREXPLOREACHS[EXPLOREGORGROND] = 95
DRAENOREXPLOREACHS[EXPLORENAGRAND] = 95
DRAENOREXPLOREACHS[EXPLORESHADOWMOONVALLEY] = 90
DRAENOREXPLOREACHS[EXPLORESPIRESOFARAK] = 95
DRAENOREXPLOREACHS[EXPLORETALADOR] = 95
DRAENOREXPLOREACHS[GRANDTREASUREHUNTER] = 95
DRAENOREXPLOREACHS[MASTERTREASUREHUNTER] = 95
DRAENOREXPLOREACHS[TREASUREHUNTER] = 92
DRAENOREXPLOREACHS[DRAENORPATHFINDER] = 98
DRAENOREXPLOREACHS[JUNGLETREASUREHUNTER] = 98
DRAENOREXPLOREACHS[JUNGLETREASUREMASTER] = 98
DRAENOREXPLOREACHS[JUNGLEHUNTER] = 98
DRAENOREXPLOREACHS[JUNGLESTALKER] = 98
DRAENOREXPLOREACHS[EXPLORETANAANJUNGLE] = 98
DRAENOREXPLOREACHS[ICAMEICLAWEDICONQUERED] = 98
DRAENOREXPLOREACHS[HELLBANE] = 98
DRAENOREXPLOREACHS[EXPLOREDRAENOR] = 100
DRAENOREXPLOREACHS[FIELDPHOTOGRAPHER] = 100
DRAENOREXPLOREACHS[WORLDEXPLORER] = 100
DRAENOREXPLOREACHS[WAKETHEDRAGON] = 92

ADEMIDOSOFREALITY=9437
AVOIDANCE=9433
ANCIENTNOMORE=9678
ARAKSTAR=9605
BOBBINGFORORCS=9635
BREAKEROFCHAINS=9533
BROKEBACKPRECIPICE=9571
BURIEDTREASURES=9548
BURNITTOTHEGROUND=9667
BYFIREBEMERGED=9537
CHARGEDUP=9634
CUTOFFTHEHEAD=9633
DELECTABLEORGREDELICACIES=9534
EGGSINONEBASKET=9612
FIGHTTHEPOWER=9655
FISHGOTTASWIMBIRDSGOTTAEAT=9613
GOODNESSGRACIOUS=9486
HERALDSOFTHELEGION=9638
HISTORYOFVIOLENCE=9610
IWANTMORETALADOR=9674
IWASFRAMED=9483
INPLAINSIGHT=9656
IRONWINGS=9659
ITSTHESTONES=9436
KINGOFTHEMONSTERS=9601
MAKEITABONUS=9607
MAKINGTHECUT=9617
MEANANDGREEN=9654
MONSTERMASH=9600
ONEOFUSONEOFUS=9434
PICKYPALATE=9663
PILLARSOFDRAENOR=9658
PLANNEDTOFAIL=9711
POISONINGTHEWELL=9710
POORCOMMUNICATION=9637
SLAGNAROK=9536
TAKEFROMTHEMEVERYTHING=9435
THATWASENTIRELYUNNECESSARY=9535
THEPOWERISYOURS=9632
SONGOFSILENCE=9541
UNITEDWESTAND=9636
WITHANAGRANDCHERRYONTOP=9615
WOULDYOULIKEAPAMPHLET=9432
YOUCANTMAKEAGIANTOMELETTE=9479
YOUHAVEBEENRYLAKINATED=9481


GORGRONDACHS = {}
GORGRONDACHS[GORGRONDMONSTERHUNTER] = 93
GORGRONDACHS[SHREDDERMANIAC] = 93
GORGRONDACHS[PROVEYOURSTRENGTH] = 93


IFOUNDPEPE=10053
TANGERINETRAVELLER=10770
WHATASTRANGEINTERDIMENSIONALTRIPITSBEEN=9838
ARAREFRIEND=9130
ANEPICBUDDY=9131
FOLLOWTHELEADER=9107
FEARLESSLEADER=9109
COMMANDERGARRISON=9494
WHEREYOUGOTHEYWILLFOLLOW=9108

DRAENORQUESTACHS = {}
DRAENORQUESTACHS[ADEMIDOSOFREALITY]=93
DRAENORQUESTACHS[AVOIDANCE]=93
DRAENORQUESTACHS[ANCIENTNOMORE]=93
DRAENORQUESTACHS[BOBBINGFORORCS]=93
DRAENORQUESTACHS[BREAKEROFCHAINS]=93
DRAENORQUESTACHS[BROKEBACKPRECIPICE]=93
DRAENORQUESTACHS[BURIEDTREASURES]=93
DRAENORQUESTACHS[BYFIREBEMERGED]=93
DRAENORQUESTACHS[CHARGEDUP]=93
DRAENORQUESTACHS[CUTOFFTHEHEAD]=94
DRAENORQUESTACHS[DELECTABLEORGREDELICACIES]=93
DRAENORQUESTACHS[EGGSINONEBASKET]=94
DRAENORQUESTACHS[FIGHTTHEPOWER]=94
DRAENORQUESTACHS[FISHGOTTASWIMBIRDSGOTTAEAT]=93
DRAENORQUESTACHS[GOODNESSGRACIOUS]=92
DRAENORQUESTACHS[HERALDSOFTHELEGION]=92
DRAENORQUESTACHS[HISTORYOFVIOLENCE]=92
DRAENORQUESTACHS[IWANTMORETALADOR]=92
DRAENORQUESTACHS[IWASFRAMED]=92
DRAENORQUESTACHS[INPLAINSIGHT]=92
DRAENORQUESTACHS[IRONWINGS]=92
DRAENORQUESTACHS[ITSTHESTONES]=92
DRAENORQUESTACHS[KINGOFTHEMONSTERS]=92
DRAENORQUESTACHS[MAKEITABONUS]=92
DRAENORQUESTACHS[MAKINGTHECUT]=92
DRAENORQUESTACHS[MONSTERMASH]=92
DRAENORQUESTACHS[ONEOFUSONEOFUS]=92
DRAENORQUESTACHS[POORCOMMUNICATION]=92
DRAENORQUESTACHS[SLAGNAROK]=92
DRAENORQUESTACHS[TAKEFROMTHEMEVERYTHING]=92
DRAENORQUESTACHS[THATWASENTIRELYUNNECESSARY]=92
DRAENORQUESTACHS[THEPOWERISYOURS]=92
DRAENORQUESTACHS[SONGOFSILENCE]=92
DRAENORQUESTACHS[UNITEDWESTAND]=92
DRAENORQUESTACHS[WITHANAGRANDCHERRYONTOP]=92
DRAENORQUESTACHS[WOULDYOULIKEAPAMPHLET]=92
DRAENORQUESTACHS[YOUCANTMAKEAGIANTOMELETTE]=92
DRAENORQUESTACHS[YOUHAVEBEENRYLAKINATED]=92
DRAENORQUESTACHS[IFOUNDPEPE]=92
DRAENORQUESTACHS[TANGERINETRAVELLER]=92
DRAENORQUESTACHS[WHATASTRANGEINTERDIMENSIONALTRIPITSBEEN]=92
DRAENORQUESTACHS[ARAREFRIEND]=90
DRAENORQUESTACHS[ANEPICBUDDY]=90
DRAENORQUESTACHS[FOLLOWTHELEADER]=90
DRAENORQUESTACHS[FEARLESSLEADER]=92
DRAENORQUESTACHS[COMMANDERGARRISON]=92
DRAENORQUESTACHS[WHEREYOUGOTHEYWILLFOLLOW]=90
--ALLY

SHADOWMOONVALLEYACHS = {}
SHADOWMOONVALLEYACHS[EXPLORESHADOWMOONVALLEY] = 90

SPIRESOFARAKACHS = {}
SPIRESOFARAKACHS[ARAKSTAR] = 90

EVERBLOOMWILDSACHS = {}
EVERBLOOMWILDSACHS[BURNITTOTHEGROUND] = 90
EVERBLOOMWILDSACHS[MEANANDGREEN] = 90
EVERBLOOMWILDSACHS[PICKYPALATE] = 90
EVERBLOOMWILDSACHS[PILLARSOFDRAENOR] = 90

ASIWALKTHROUGHTHEVALLEY=8845
BETWEENARAKANDAHARDPLACEA=8925
DONTLETTHETALADOORHITYOUA=8920
NAGRANDEURA=8927
ONTHESHADOWSTRAILA=9528
PUTTINGTHEGOREINGORGRONDA=8923
SECURINGDRAENORA=9564
SHOOTFORTHEMOON=9602
GARRISONCAMPAIGNA=9491
WELCOMETODRAENORA=8921
WRITINGINTHESNOWA=9530
ADVANCEDHUSBANDRYA=9539
CHOPPINEVENMORELEGSA=9078
STABLEMASTERA=9540
WARLORDOFDRAENORA=9738
CHARTINGACOURSEA=10256

DRAENORALLYQUESTACHS = {}

DRAENORALLYQUESTACHS [ASIWALKTHROUGHTHEVALLEY] = 90
DRAENORALLYQUESTACHS [BETWEENARAKANDAHARDPLACEA] = 93
DRAENORALLYQUESTACHS [DONTLETTHETALADOORHITYOUA] = 93
DRAENORALLYQUESTACHS [NAGRANDEURA] = 95
DRAENORALLYQUESTACHS [ONTHESHADOWSTRAILA] = 90
DRAENORALLYQUESTACHS [PUTTINGTHEGOREINGORGRONDA] = 93
DRAENORALLYQUESTACHS [SECURINGDRAENORA] = 95
DRAENORALLYQUESTACHS [SHOOTFORTHEMOON] = 90
DRAENORALLYQUESTACHS [GARRISONCAMPAIGNA] = 95
DRAENORALLYQUESTACHS [WELCOMETODRAENORA] = 90
DRAENORALLYQUESTACHS [WRITINGINTHESNOWA] = 93
DRAENORALLYQUESTACHS [ADVANCEDHUSBANDRYA] = 90
DRAENORALLYQUESTACHS [CHOPPINEVENMORELEGSA] = 90
DRAENORALLYQUESTACHS [STABLEMASTERA] = 90
DRAENORALLYQUESTACHS [WARLORDOFDRAENORA] = 90
DRAENORALLYQUESTACHS [CHARTINGACOURSEA]=93

--HORDE

BETWEENARAKANDAHARDPLACEH=8926
DONTLETTHETALADOORHITYOUH=8919
FROSTFIREFRIDGE=9606
NAGRANDEURH=8928
ONTHESHADOWSTRAILH=9529
PUTTINGTHEGOREINGORGRONDH=8924
SECURINGDRAENORH=9562
GARRISONCAMPAIGNH=9492
WELCOMETODRAENORH=8922
WRITINGINTHESNOWH=9531
YOULLGETCAUGHTUPINTHEFROSTFIRE=8671
ADVANCEDHUSBANDRYH=9705
CHOPPINEVENMORELEGSH=9080
STABLEMASTERH=9706
WARLORDOFDRAENORH=9508
CHARTINGACOURSEH=10258


DRAENORHORDEQUESTACHS = {}
DRAENORHORDEQUESTACHS [BETWEENARAKANDAHARDPLACEH] = 92
DRAENORHORDEQUESTACHS [DONTLETTHETALADOORHITYOUH] = 92
DRAENORHORDEQUESTACHS [NAGRANDEURH] = 92
DRAENORHORDEQUESTACHS [PUTTINGTHEGOREINGORGRONDH] = 92
DRAENORHORDEQUESTACHS [SECURINGDRAENORH] = 95
DRAENORHORDEQUESTACHS [GARRISONCAMPAIGNH] = 100
DRAENORHORDEQUESTACHS [WELCOMETODRAENORH] = 90
DRAENORHORDEQUESTACHS [WRITINGINTHESNOWH] = 92
DRAENORHORDEQUESTACHS [YOULLGETCAUGHTUPINTHEFROSTFIRE] = 90
DRAENORHORDEQUESTACHS [ADVANCEDHUSBANDRYH] = 90
DRAENORHORDEQUESTACHS [CHOPPINEVENMORELEGSH] = 90
DRAENORHORDEQUESTACHS [STABLEMASTERH] = 90
DRAENORHORDEQUESTACHS [WARLORDOFDRAENORH] = 90
DRAENORHORDEQUESTACHS [CHARTINGACOURSEH]=93

--neutral
STAYINGREGULAR=8933
BOTANIINVASION=9208
BRONZEDEFENDER=9162
GOLDENDEFENDER=9165
GORENINVASION=9207
IMPERVIOUSDEFENDER=9827
INVASIONSPECIALIST=9167
INVASIONWHATINVASION=9543
INVASIONSAREBETTERWITHFRIENDS=9244
IRONHORDEINVASION=9205
ITSANINVASION=9152
MASTERANDCOMMANDER=9858
MASTERDEFENDER=9209
OGREINVASION=9204
PLATINUMDEFENDER=9826
SAVETHOSEBUILDINGS=9181
SHADOWCOUNCILINVASION=9203
SHADOWMOONCLANINVASION=9206
SILVERDEFENDER=9164
DRAENORPETBRAWLER=9264
MASTERDRAENORCRAFTER=9246
MASTEROFAPEXIS=9265
ARAREMISSION=9141
EXPLORATIONMISSIONMASTER=9900
EXPLORATIONMISSIONSPECIALIST=9150
KEEPINGITRARE=9142
MISSIONSPECIALIST=9147
ONAFEWMISSIONS=9134
ONALOTOFMISSIONS=9138
ONAMASSIVENUMBEROFMISSIONS=9139
ONAMETRICTONOFMISSIONS=9140
ONAMISSION=9133
PATROLMISSIONSPECIALIST=9146
PATROLLINGDRAENOR=9523
THERARERTHEBETTER=9143
TREASUREMASTER=9524
TREASUREMISSIONSPECIALIST=9145



--alliance
AZEROTHSTOPTWENTYTUNESA=9912
DONTCALLMEJUNIORA=9928
EVENMOREPLOTSA=9101
FULLDISCOGRAPHYA=10015
GARRISONBUDDIESA=9210
MOREPLOTSA=9100
TENHITTUNESA=9828
DEFENDEROFDRAENORA=9630
MYTHICDRAENORRAIDERA=9631

--horde
AZEROTHSTOPTWENTYTUNESH=9914
DONTCALLMEJUNIORH=9901
EVENMOREPLOTSH=9546
FULLDISCOGRAPHYH=10016
GARRISONBUDDIESH=9132
MOREPLOTSH=9545
TENHITTUNESH=9897
DEFENDEROFDRAENORH=9248
MYTHICDRAENORRAIDERH=9255


--neutral
DRAENORGARRISONACHS = {}
DRAENORGARRISONACHS [STAYINGREGULAR] = 85
DRAENORGARRISONACHS [BOTANIINVASION] = 92
DRAENORGARRISONACHS [BRONZEDEFENDER] = 92
DRAENORGARRISONACHS [GOLDENDEFENDER] = 92
DRAENORGARRISONACHS [GORENINVASION] = 92
DRAENORGARRISONACHS [IMPERVIOUSDEFENDER] = 92
DRAENORGARRISONACHS [INVASIONSPECIALIST] = 85
DRAENORGARRISONACHS [INVASIONWHATINVASION] = 85
DRAENORGARRISONACHS [INVASIONSAREBETTERWITHFRIENDS] = 85
DRAENORGARRISONACHS [IRONHORDEINVASION] = 92
DRAENORGARRISONACHS [ITSANINVASION] = 92
DRAENORGARRISONACHS [MASTERANDCOMMANDER] = 85
DRAENORGARRISONACHS [MASTERDEFENDER] = 92
DRAENORGARRISONACHS [OGREINVASION] = 92
DRAENORGARRISONACHS [PLATINUMDEFENDER] = 92
DRAENORGARRISONACHS [SAVETHOSEBUILDINGS] = 92
DRAENORGARRISONACHS [SHADOWCOUNCILINVASION] = 92
DRAENORGARRISONACHS [SHADOWMOONCLANINVASION] = 92
DRAENORGARRISONACHS [SILVERDEFENDER] = 92
DRAENORGARRISONACHS [DRAENORPETBRAWLER] = 85
DRAENORGARRISONACHS [MASTERDRAENORCRAFTER] = 92
DRAENORGARRISONACHS [MASTEROFAPEXIS] = 90
DRAENORGARRISONACHS [ARAREMISSION] = 85
DRAENORGARRISONACHS [EXPLORATIONMISSIONMASTER] = 85
DRAENORGARRISONACHS [EXPLORATIONMISSIONSPECIALIST] = 85
DRAENORGARRISONACHS [KEEPINGITRARE] = 85
DRAENORGARRISONACHS [MISSIONSPECIALIST] = 92
DRAENORGARRISONACHS [ONAFEWMISSIONS] = 85
DRAENORGARRISONACHS [ONALOTOFMISSIONS] = 85
DRAENORGARRISONACHS [ONAMASSIVENUMBEROFMISSIONS] = 85
DRAENORGARRISONACHS [ONAMETRICTONOFMISSIONS] = 93
DRAENORGARRISONACHS [ONAMISSION] = 85
DRAENORGARRISONACHS [PATROLMISSIONSPECIALIST] = 85
DRAENORGARRISONACHS [PATROLLINGDRAENOR] = 85
DRAENORGARRISONACHS [THERARERTHEBETTER] = 92
DRAENORGARRISONACHS [TREASUREMASTER] = 97
DRAENORGARRISONACHS [TREASUREMISSIONSPECIALIST] = 92

--alliance
DRAENORALLYGARRISONACHS = {}
DRAENORALLYGARRISONACHS [AZEROTHSTOPTWENTYTUNESA] = 92
DRAENORALLYGARRISONACHS [DONTCALLMEJUNIORA] = 92
DRAENORALLYGARRISONACHS [EVENMOREPLOTSA] = 92
DRAENORALLYGARRISONACHS [FULLDISCOGRAPHYA] = 92
DRAENORALLYGARRISONACHS [GARRISONBUDDIESA] = 95
DRAENORALLYGARRISONACHS [MOREPLOTSA] = 85
DRAENORALLYGARRISONACHS [TENHITTUNESA] = 92
DRAENORALLYGARRISONACHS [DEFENDEROFDRAENORA] = 85
DRAENORALLYGARRISONACHS [MYTHICDRAENORRAIDERA] = 100


--horde
DRAENORHORDEGARRISONACHS = {}
DRAENORHORDEGARRISONACHS [AZEROTHSTOPTWENTYTUNESH] = 92
DRAENORHORDEGARRISONACHS [DONTCALLMEJUNIORH] = 92
DRAENORHORDEGARRISONACHS [EVENMOREPLOTSH] = 92
DRAENORHORDEGARRISONACHS [FULLDISCOGRAPHYH] = 92
DRAENORHORDEGARRISONACHS [GARRISONBUDDIESH] = 95
DRAENORHORDEGARRISONACHS [MOREPLOTSH] = 85
DRAENORHORDEGARRISONACHS [TENHITTUNESH] = 92
DRAENORHORDEGARRISONACHS [DEFENDEROFDRAENORH] = 92
DRAENORHORDEGARRISONACHS [MYTHICDRAENORRAIDERH] = 100

--rep

--ally rep
COUNCILOFEXARCHS=9470
SAVAGEFRIENDSA=9478
SHATARIDEFENSE=9476
TANAANDIPLOMATA=10350
WRYNNSVANGUARD=9474

--NEUTRAL REP
ARAKKOAOUTCASTS=9469
MANTLEOFTHETALONKING=9072
STEAMWHEEDLEPRESERVATIONSOCIETY=9472

--HORDE REP
FROSTWOLFORCS=9471
LAUGHINGSKULLORCS=9475
SAVAGEFRIENDSH=9477
TANANNDIPLOMATH=10349
VOLJINSSPEAR=9473

DRAENORALLYREPACHS = {}

--ally rep
DRAENORALLYREPACHS[COUNCILOFEXARCHS] = 90
DRAENORALLYREPACHS[SAVAGEFRIENDSA] = 90
DRAENORALLYREPACHS[SHATARIDEFENSE] = 90
DRAENORALLYREPACHS[TANAANDIPLOMATA] = 90
DRAENORALLYREPACHS[WRYNNSVANGUARD] = 90

DRAENORNEUTRALREPACHS = {}

--NEUTRAL REP
DRAENORNEUTRALREPACHS[ARAKKOAOUTCASTS] = 90
DRAENORNEUTRALREPACHS[MANTLEOFTHETALONKING] = 90
DRAENORNEUTRALREPACHS[STEAMWHEEDLEPRESERVATIONSOCIETY] = 90


DRAENORHORDEREPACHS = {}

--HORDE REP
DRAENORHORDEREPACHS[FROSTWOLFORCS] = 90
DRAENORHORDEREPACHS[LAUGHINGSKULLORCS] = 90
DRAENORHORDEREPACHS[SAVAGEFRIENDSH] = 90
DRAENORHORDEREPACHS[TANANNDIPLOMATH] = 90
DRAENORHORDEREPACHS[VOLJINSSPEAR] = 90

--BRAWLERSGUILD

BOTTLESERVICE=7944
HATERSGONNAHATE=7945
IMYOURNUMBERONEFAN=7943

BRAWLERSGUILDACHS = {}
BRAWLERSGUILDACHS[BOTTLESERVICE] = 90
BRAWLERSGUILDACHS[HATERSGONNAHATE] = 90
BRAWLERSGUILDACHS[IMYOURNUMBERONEFAN] = 90

--BG ALLIANCE
BRAWLINANDSHOTCALLINA=9170
COLLECTYOURDECKA=8339
DECKYOURCOLLECTIONA=9176
NOWYOUREJUSTSHOWINGOFFA=9171
RABBLERABBLERABBLEA=7949
FIRSTRULEOFBRAWLERSGUILDA=7947
SECONDRULEOFBRAWLERSGUILDA=9169
YOUARENOTYOURLEGPLATESA=9168

BRAWLERSALLYACHS = {}

BRAWLERSALLYACHS[BRAWLINANDSHOTCALLINA] = 90
BRAWLERSALLYACHS[COLLECTYOURDECKA] = 90
BRAWLERSALLYACHS[DECKYOURCOLLECTIONA] = 90
BRAWLERSALLYACHS[NOWYOUREJUSTSHOWINGOFFA] = 90
BRAWLERSALLYACHS[RABBLERABBLERABBLEA] = 90
BRAWLERSALLYACHS[FIRSTRULEOFBRAWLERSGUILDA] = 90
BRAWLERSALLYACHS[SECONDRULEOFBRAWLERSGUILDA] = 90
BRAWLERSALLYACHS[YOUARENOTYOURLEGPLATESA] = 90



--BG HORDE
BRAWLINANDSHOTCALLINH=9174
COLLECTYOURDECKH=8342
DECKYOURCOLLECTIONH=9177
NOWYOUREJUSTSHOWINGOFFH=9175
RABBLERABBLERABBLEH=7950
FIRSTRULEOFBRAWLERSGUILDH=7948
SECONDRULEOFBRAWLERSGUILDH=9173
YOUARENOTYOURLEGPLATESH=9172

BRAWLERSHORDEACHS = {}

BRAWLERSHORDEACHS[BRAWLINANDSHOTCALLINH] = 90
BRAWLERSHORDEACHS[COLLECTYOURDECKH] = 90
BRAWLERSHORDEACHS[DECKYOURCOLLECTIONH] = 90
BRAWLERSHORDEACHS[NOWYOUREJUSTSHOWINGOFFH] = 90
BRAWLERSHORDEACHS[RABBLERABBLERABBLEH] = 90
BRAWLERSHORDEACHS[FIRSTRULEOFBRAWLERSGUILDH] = 90
BRAWLERSHORDEACHS[SECONDRULEOFBRAWLERSGUILDH] = 90
BRAWLERSHORDEACHS[YOUARENOTYOURLEGPLATESH] = 90

BUILDER=9095
CHOPPINGSOMELOGS=9076
CHOPPINGSOMEMORELOGS=9077
DRAFTSMAN=9125
FIGHTKILLSALUTE=9639
FINDINGYOURWAYSTONES=9497
GARRISONARCHITECT=9094
GRANDMASTERDRAFTSMAN=9128
INTROTOHUSBANDRY=9538
KEEPINGBUSY=9097
MASTERBUILDER=9096
MASTERDRAFTSMAN=9126
MASTEROFMOUNTS=9526
MASTERTRAPPER=9565
MOVINGONUP=9098
SALVAGINGPAYSOFF=9468
STAYAWHILEANDLISTEN=9703
TERRIFICTECHNOLOGY=9527
BONECOLLECTOR=9495
TRAPGAME=9450
TIMEFORANUPGRADE=9099
TRAPSUPERSTAR=9452
WORKINGSOMEORDERS=9405
TRAPPERSDELIGHT=9451
UPGRADINGTHEMILL=9429
WINGMAN=9498
WINGMEN=9499
WORKINGMANYORDERS=9407
WORKINGMOREORDERS=9406

GARRISONBUILDINGNEUTRALACHS = {}
GARRISONBUILDINGNEUTRALACHS[BUILDER] = 90
GARRISONBUILDINGNEUTRALACHS[CHOPPINGSOMELOGS] = 90
GARRISONBUILDINGNEUTRALACHS[CHOPPINGSOMEMORELOGS] = 90
GARRISONBUILDINGNEUTRALACHS[DRAFTSMAN] = 90
GARRISONBUILDINGNEUTRALACHS[FIGHTKILLSALUTE] = 92
GARRISONBUILDINGNEUTRALACHS[FINDINGYOURWAYSTONES] = 90
GARRISONBUILDINGNEUTRALACHS[GARRISONARCHITECT] = 90
GARRISONBUILDINGNEUTRALACHS[GRANDMASTERDRAFTSMAN] = 90
GARRISONBUILDINGNEUTRALACHS[INTROTOHUSBANDRY] = 90
GARRISONBUILDINGNEUTRALACHS[KEEPINGBUSY] = 90
GARRISONBUILDINGNEUTRALACHS[MASTERBUILDER] = 90
GARRISONBUILDINGNEUTRALACHS[MASTERDRAFTSMAN] = 90
GARRISONBUILDINGNEUTRALACHS[MASTEROFMOUNTS] = 92
GARRISONBUILDINGNEUTRALACHS[MASTERTRAPPER] = 90
GARRISONBUILDINGNEUTRALACHS[MOVINGONUP] = 90
GARRISONBUILDINGNEUTRALACHS[SALVAGINGPAYSOFF] = 90
GARRISONBUILDINGNEUTRALACHS[STAYAWHILEANDLISTEN] = 90
GARRISONBUILDINGNEUTRALACHS[TERRIFICTECHNOLOGY] = 92
GARRISONBUILDINGNEUTRALACHS[BONECOLLECTOR] = 90
GARRISONBUILDINGNEUTRALACHS[TRAPGAME] = 90
GARRISONBUILDINGNEUTRALACHS[TIMEFORANUPGRADE] = 90
GARRISONBUILDINGNEUTRALACHS[TRAPSUPERSTAR] = 92
GARRISONBUILDINGNEUTRALACHS[WORKINGSOMEORDERS] = 90
GARRISONBUILDINGNEUTRALACHS[TRAPPERSDELIGHT] = 90
GARRISONBUILDINGNEUTRALACHS[UPGRADINGTHEMILL] = 90
GARRISONBUILDINGNEUTRALACHS[WINGMAN] = 90
GARRISONBUILDINGNEUTRALACHS[WINGMEN] = 90
GARRISONBUILDINGNEUTRALACHS[WORKINGMANYORDERS] = 90
GARRISONBUILDINGNEUTRALACHS[WORKINGMOREORDERS] = 90

--SHIPYARD
IRONSIDES=10165
MASTEROFTHESEAS=10164
NAVALARMADA=10168
NAVALBONUSEXPERT=10036
NAVALBONUSSPECIALIST=10017
NAVALCOMBATEXPERT=10154
NAVALCOMBATSPECIALIST=10156
NAVALFLEET=10169
NAVALMECHANICS=10166
NAVALSIEGEEXPERT=10155
NAVALSIEGESPECIALIST=10161
NAVALTRAININGEXPERT=10163
NAVALTRAININGSPECIALIST=10162
NAVALTREASUREEXPERT=10160
NAVALTREASURESPECIALIST=10159
SEAMAN=10170
SETSAIL=10177

GARRISONSHIPYARDNEUTRALACHS = {}
GARRISONSHIPYARDNEUTRALACHS[IRONSIDES] = 92
GARRISONSHIPYARDNEUTRALACHS[MASTEROFTHESEAS] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALARMADA] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALBONUSEXPERT] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALBONUSSPECIALIST] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALCOMBATEXPERT] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALCOMBATSPECIALIST] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALFLEET] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALMECHANICS] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALSIEGEEXPERT] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALSIEGESPECIALIST] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALTRAININGEXPERT] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALTRAININGSPECIALIST] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALTREASUREEXPERT] = 92
GARRISONSHIPYARDNEUTRALACHS[NAVALTREASURESPECIALIST] = 92
GARRISONSHIPYARDNEUTRALACHS[SEAMAN] = 92
GARRISONSHIPYARDNEUTRALACHS[SETSAIL] = 92



FROSTFIREACHS = {}
FROSTFIREACHS[PLANNEDTOFAIL]=90
FROSTFIREACHS[POISONINGTHEWELL]=90
FROSTFIREACHS[ONTHESHADOWSTRAILH] = 90
FROSTFIREACHS[FROSTFIREFRIDGE] = 90
