
ARAREFRIEND=9130
ANEPICBUDDY=9131
COMMANDERGARRISON=9494
FEARLESSLEADER=9109
FILLINGTHERANKS=9129
FOLLOWTHELEADER=9107
FOLLOWINGUP=9110
ITEMLEVELARMY=9213
ITEMLEVELFORCE=9243
MYITEMLEVELISHIGHERTHANYOURS=9211
MYITEMLEVELISWAYHIGHERTHANYOURS=9212
RAISINGTHEBAR=9111
WHEREYOUGOTHEYWILLFOLLOW=9108

GARRISONFOLLOWERSACHS = {}
GARRISONFOLLOWERSACHS[ARAREFRIEND] = 90
GARRISONFOLLOWERSACHS[ANEPICBUDDY] = 90
GARRISONFOLLOWERSACHS[COMMANDERGARRISON] = 90
GARRISONFOLLOWERSACHS[FEARLESSLEADER] = 90
GARRISONFOLLOWERSACHS[FILLINGTHERANKS] = 90
GARRISONFOLLOWERSACHS[FOLLOWTHELEADER] = 90
GARRISONFOLLOWERSACHS[FOLLOWINGUP] = 90
GARRISONFOLLOWERSACHS[ITEMLEVELARMY] = 90
GARRISONFOLLOWERSACHS[ITEMLEVELFORCE] = 90
GARRISONFOLLOWERSACHS[MYITEMLEVELISHIGHERTHANYOURS] = 90
GARRISONFOLLOWERSACHS[MYITEMLEVELISWAYHIGHERTHANYOURS] = 90
GARRISONFOLLOWERSACHS[RAISINGTHEBAR] = 90
GARRISONFOLLOWERSACHS[WHEREYOUGOTHEYWILLFOLLOW] = 90

