

FILLINGTHERANKS=9129
FOLLOWINGUP=9110
ITEMLEVELARMY=9213
ITEMLEVELFORCE=9243
MYITEMLEVELISHIGHERTHANYOURS=9211
MYITEMLEVELISWAYHIGHERTHANYOURS=9212
RAISINGTHEBAR=9111

GARRISONFOLLOWERSACHS = {}
GARRISONFOLLOWERSACHS[FILLINGTHERANKS] = 92
GARRISONFOLLOWERSACHS[FOLLOWINGUP] = 92
GARRISONFOLLOWERSACHS[ITEMLEVELARMY] = 92
GARRISONFOLLOWERSACHS[ITEMLEVELFORCE] = 92
GARRISONFOLLOWERSACHS[MYITEMLEVELISHIGHERTHANYOURS] = 92
GARRISONFOLLOWERSACHS[MYITEMLEVELISWAYHIGHERTHANYOURS] = 92
GARRISONFOLLOWERSACHS[RAISINGTHEBAR] = 92

