--holidays
PILGRIMSBOUNTY = "Pilgrim's Bounty"
WINTERVEIL = "Feast of Winter Veil"
STRANGLETHORNFISHING = "Stranglethorn Fishing Extravaganza"
KALUAKFISHING = "Kalu'ak Fishing Derby"
DARKMOONFAIRE = "Darkmoon Faire"
NOBLEGARDEN = "Noblegarden"
CHILDRENSWEEK = "Children's Week"
MIDSUMMER = "Midsummer Fire Festival"
BREWFEST = "Brewfest"
HALLOWSEND = "Hallows End"
LUNARFESTIVAL = "Lunar Festival"
LOVEISINTHEAIR = "Love is in the Air"
DAYOFTHEDEAD = "Day of the Dead"
BATTLEGROUNDBONUSEVENT = "Battleground Bonus Event"
DRAENORDUNGEONBONUSEVENT = "Draenor Dungeon Event"
PETBATTLEBONUSEVENT = "Pet Battle Bonus Event"
PIRATESDAY = "Pirate's Day"
TIMEWALKINGEVENT = "Timewalking Dungeon Event"
APEXISBONUSEVENT = "Apexis Bonus Event"

--holidays
FOODFIGHT = 3579
NOWWERECOOKINGA = 3576
NOWWERECOOKINGH = 3577 
SHARINGISCARING = 3558
TURKINATOR = 3578
PILGRIMSPROGRESSH = 3597
PILGRIMSPAUNCHH = 3557
PILGRIMSPERILH = 3581
PILGRIMSPROGRESSA = 3596 
PILGRIMSPAUNCHA = 3556
PILGRIMSPERILA = 3580
TURKEYLURKEY = 3559
TEROKKARTURKEY = 3582
PILGRIMA = 3478


TISTHESEASON = 277
AFROSTYSHAKE = 1690
CRASHINANDTHRASHIN =1295
HEKNOWSIFYOUVEBEENNAUGHTY = 1689
WINTERVEILGOURMET = 1688
WITHALITTLEHELPER = 252
LETITSNOW = 1687
ONMETZEN = 273
SIMPLYABOMINABLE = 279
FALALALAOGRILA = 1282
SCROOGEH = 259
BROSBEFOREHOHOHOSH =1685
ACAROLINGWEWILLGOH = 5854
BBKINGH=4437
MERRYMAKERH=1691
SCROOGEA=1255
BROSBEFOREHOHOHOSA=1686
ACAROLINGWEWILLGOA=5853
BBKINGA=4436
DANGERZONE=8699



--childrensweek
AWISNTITCUTE=1792
BADEXAMPLE=1788
DAILYCHORES=1789
HAILTOTHEKINGBABY=1790
HOMEALONE=1791
SCHOOLOFHARDKNOCKS=1786
VETERANNANNY=275
FORTHECHILDREN=1793



--MIDSUMMER

   BURNINGHOTPOLEDANCE=271
   KINGOFTHEFIREFESTIVAL=1145
   ICETHEFROSTLORD=263
   TORCHJUGGLER=272
   EXTINGUISHINGEKA=1028
    EXTINGUISHINGKA=1029
    EXTINGUISHINGNORTHA=6007
    EXTINGUISHINGOUTLANDA=1030
    EXTINGUISHINGCATAA=6013
    FLAMEKEEPEREKA=1022
    FLAMEKEEPERKA=1023
    FLAMEKEEPEROUTLANDA=1024
    FLAMEKEEPERNORTHA=6008
    FLAMEKEEPERCATAA= 6011
    EXTINGUISHINGEKH=1031
    EXTINGUISHINGKH=1032
    EXTINGUISHINGNORTHH=6010
    EXTINGUISHINGOUTLANDH=1033
    EXTINGUISHINGCATAH=6014
    FLAMEKEEPEREKH=1025
    FLAMEKEEPERKH=1026
    FLAMEKEEPEROUTLANDH=1027
    FLAMEKEEPERNORTHH=6009
    FLAMEKEEPERCATAH=6012
DESECRATIONOFTHEHORDE=1035
DESECRATIONOFTHEALLIANCE=1037
FLAMEKEEPEROFPANDARIA=8044--HORDE
FLAMEWARDENOFPANDARIA=8045
FIRESOFAZEROTHA=1034
FIRESOFAZEROTHH=1036
EXTINGUISHINGPANDARIAH=8043
EXTINGUISHINGPANDARIAA=8042
FLAMEKEEPER=1039
FLAMEWARDEN=1038


MIDSUMMERACHS = {}
MIDSUMMERACHS[TORCHJUGGLER] = 1
MIDSUMMERACHS[EXPLOREEASTERNKINGDOMS] = 1
MIDSUMMERACHS[EXPLOREKALIMDOR] = 1
MIDSUMMERACHS[BURNINGHOTPOLEDANCE] = 1
MIDSUMMERACHS[KINGOFTHEFIREFESTIVAL] = 1
MIDSUMMERACHS[EXPLORENORTHREND] = 40
MIDSUMMERACHS[EXPLOREOUTLAND] = 40
MIDSUMMERACHS[EXPLORECATACLYSM] = 60
MIDSUMMERACHS[ICETHEFROSTLORD] = 82
MIDSUMMERACHS[FLAMEWARDEN] = 82
MIDSUMMERACHS[FLAMEKEEPER] = 1



AMASKFORALLOCCASIONS=284
BRINGMETHEHEADOFOHWAIT=255
CHECKYOURHEAD=291
GNERDRAGE=1261
OUTWITHIT=288
SINISTERCALLING=292
THATSPARKLINGSMILE=981
THEMASKTASK=979
THEMASQUERADE=283
THESAVIOROFHALLOWSEND=289
TRICKORTREAT=972
TRICKSANDTREATSOFAZEROTH=971
HALLOWEDBETHYNAME=1656
AFRIGHTENINGFRIEND=10365

HALLOWSENDNEUTRAL = {}
HALLOWSENDNEUTRAL[AMASKFORALLOCCASIONS] = 60 --at least get a FLYING mount first
HALLOWSENDNEUTRAL[BRINGMETHEHEADOFOHWAIT] = 70
HALLOWSENDNEUTRAL[CHECKYOURHEAD] = 10 -- pvp
HALLOWSENDNEUTRAL[GNERDRAGE] = 10 --pvp
HALLOWSENDNEUTRAL[OUTWITHIT] = 1
HALLOWSENDNEUTRAL[THATSPARKLINGSMILE] = 1
HALLOWSENDNEUTRAL[THEMASKTASK] = 1
HALLOWSENDNEUTRAL[THESAVIOROFHALLOWSEND] = 1
HALLOWSENDNEUTRAL[TRICKORTREAT] = 1
HALLOWSENDNEUTRAL[SINISTERCALLING] = 60  -- v difficult to get now
HALLOWSENDNEUTRAL[THEMASQUERADE] = 60  -- v difficult to get now
HALLOWSENDNEUTRAL[TRICKSANDTREATSOFAZEROTH] = 60
HALLOWSENDNEUTRAL[HALLOWEDBETHYNAME] = 60
HALLOWSENDNEUTRAL[AFRIGHTENINGFRIEND] = 1



ROTTENHALLOWA=1040
TRICKSANDTREATSOFEASTERNKINGDOMSA=966
TRICKSANDTREATSOFKALIMDORA=963
TRICKSANDTREATSOFNORTHRENDA=5836
TRICKSANDTREATSOFOUTLANDA=969
TRICKSANDTREATSOFPANDARIAA=7601
TRICKSANDTREATSOFTHECATACLYSMA=5837

HALLOWSENDALLIANCE = {}
HALLOWSENDALLIANCE [ROTTENHALLOWA]= 40 -- need to go to horde
HALLOWSENDALLIANCE [TRICKSANDTREATSOFEASTERNKINGDOMSA]= 50
HALLOWSENDALLIANCE [TRICKSANDTREATSOFKALIMDORA]= 50
HALLOWSENDALLIANCE [TRICKSANDTREATSOFNORTHRENDA]= 70
HALLOWSENDALLIANCE [TRICKSANDTREATSOFOUTLANDA]= 60
HALLOWSENDALLIANCE [TRICKSANDTREATSOFPANDARIAA]= 80
HALLOWSENDALLIANCE [TRICKSANDTREATSOFTHECATACLYSMA]= 80


ROTTENHALLOWH=1041
TRICKSANDTREATSOFEASTERNKINGDOMSH=967
TRICKSANDTREATSOFKALIMDORH=965
TRICKSANDTREATSOFNORTHRENDH=5835
TRICKSANDTREATSOFOUTLANDH=968
TRICKSANDTREATSOFPANDARIAH=7602
TRICKSANDTREATSOFTHECATACLYSMH=5838

HALLOWSENDHORDE = {}
HALLOWSENDHORDE [ROTTENHALLOWH]= 40 -- need to go to alliance
HALLOWSENDHORDE [TRICKSANDTREATSOFEASTERNKINGDOMSH]= 50
HALLOWSENDHORDE [TRICKSANDTREATSOFKALIMDORH]= 50
HALLOWSENDHORDE [TRICKSANDTREATSOFNORTHRENDH]= 70
HALLOWSENDHORDE [TRICKSANDTREATSOFOUTLANDH]= 60
HALLOWSENDHORDE [TRICKSANDTREATSOFPANDARIAH]= 80
HALLOWSENDHORDE [TRICKSANDTREATSOFTHECATACLYSMH] = 80



--lunar festival
ACOINOFANCESTRY=605
FIVECOINSOFANCESTRY=606
TENCOINSOFANCESTRY=607
TWENTYFIVECOINSOFANCESTRY=608
FIFTYCOINSOFANCESTRY=609
ELDERSOFCATACLYSM=6006
ELDERSOFEASTERNKINGDOMS=912
ELDERSOFKALIMDOR=911
ELDERSOFNORTHREND=1396
ELDERSOFTHEALLIANCE=915
ELDERSOFTHEDUNGEONS=910
ELDERSOFTHEHORDE=914
ELUNESBLESSING=937
FRENZIEDFIRECRACKER=1552
LUNARFESTIVALFINERY=626
ROCKETSREDGLARE=1281
HONORONESELDERS = 913

LUNARFESTIVALNEUTRAL = {}
LUNARFESTIVALNEUTRAL[ACOINOFANCESTRY] = 1
LUNARFESTIVALNEUTRAL[FIVECOINSOFANCESTRY] = 1
LUNARFESTIVALNEUTRAL[TENCOINSOFANCESTRY] = 1
LUNARFESTIVALNEUTRAL[TWENTYFIVECOINSOFANCESTRY] = 1
LUNARFESTIVALNEUTRAL[FIFTYCOINSOFANCESTRY] =30
LUNARFESTIVALNEUTRAL[ELDERSOFCATACLYSM] = 70
LUNARFESTIVALNEUTRAL[ELDERSOFEASTERNKINGDOMS] = 40 --needs 70 for alliance
LUNARFESTIVALNEUTRAL[ELDERSOFKALIMDOR] = 40
LUNARFESTIVALNEUTRAL[ELDERSOFNORTHREND] = 65
LUNARFESTIVALNEUTRAL[ELDERSOFTHEALLIANCE] = 1
LUNARFESTIVALNEUTRAL[ELDERSOFTHEDUNGEONS] = 60
LUNARFESTIVALNEUTRAL[ELDERSOFTHEHORDE] = 1
LUNARFESTIVALNEUTRAL[ELUNESBLESSING] = 1
LUNARFESTIVALNEUTRAL[FRENZIEDFIRECRACKER] = 1
LUNARFESTIVALNEUTRAL[LUNARFESTIVALFINERY] = 1
LUNARFESTIVALNEUTRAL[ROCKETSREDGLARE] = 1
LUNARFESTIVALNEUTRAL[HONORONESELDERS] = 60


--noblegarden
IFOUNDONE=2676
CHOCOLATELOVER=2417
CHOCOHOLIC=2418
DRESSEDFORTHEOCCASION=249
SUNDAYSFINEST=248
BLUSHINGBRIDE=2576
NOBLEGARDENA=2421
SPRINGFLINGA=2419
SPRINGFLINGH=2497
NOBLEGARDENH=2420
SHAKEYOURBUNNYMAKER=2422
DESERTROSE=2436
HARDBOILED=2416
NOBLEGARDENER=2798

NOBLEGARDENNEUTRAL = {}
NOBLEGARDENNEUTRAL[IFOUNDONE] = 1
NOBLEGARDENNEUTRAL[CHOCOLATELOVER] = 1
NOBLEGARDENNEUTRAL[CHOCOHOLIC] = 1
NOBLEGARDENNEUTRAL[DRESSEDFORTHEOCCASION] = 1
NOBLEGARDENNEUTRAL[SUNDAYSFINEST] = 1
NOBLEGARDENNEUTRAL[BLUSHINGBRIDE] = 1
NOBLEGARDENNEUTRAL[SHAKEYOURBUNNYMAKER] = 15
NOBLEGARDENNEUTRAL[DESERTROSE] = 45
NOBLEGARDENNEUTRAL[HARDBOILED] = 45
NOBLEGARDENNEUTRAL[NOBLEGARDENER] = 45

BEMINE=1701
CHARMING=260
DANGEROUSLOVE=1695
FISTFULOFLOVE=1699
IPITIEDTHEFOOL=1704
LONELY=1291
LOVELYLUCKISONYOURSIDE=1694
MYLOVEISLIKEAREDREDROSE=1703
PERMAPEDDLE=1700
SHAFTED=1188
SWEETTOOTH=1702
THEROCKETSPINKGLARE=1696
TOUGHLOVE=4624
LOVEMAGNET=9392
THEYREALLYLOVEME=9394
ITMIGHTJUSTSAVEYOURLIFE=9389
FOOLFORLOVE=1693

LOVEISINTHEAIRNEUTRAL = {}
LOVEISINTHEAIRNEUTRAL[BEMINE] = 1
LOVEISINTHEAIRNEUTRAL[LOVEMAGNET] = 1
LOVEISINTHEAIRNEUTRAL[THEYREALLYLOVEME] = 1
LOVEISINTHEAIRNEUTRAL[ITMIGHTJUSTSAVEYOURLIFE] = 1
LOVEISINTHEAIRNEUTRAL[CHARMING] = 1
LOVEISINTHEAIRNEUTRAL[DANGEROUSLOVE] = 1
LOVEISINTHEAIRNEUTRAL[FISTFULOFLOVE] = 1
LOVEISINTHEAIRNEUTRAL[IPITIEDTHEFOOL] = 1
LOVEISINTHEAIRNEUTRAL[LONELY] = 60 --DALARAN
LOVEISINTHEAIRNEUTRAL[LOVELYLUCKISONYOURSIDE] = 1
LOVEISINTHEAIRNEUTRAL[MYLOVEISLIKEAREDREDROSE] = 1
LOVEISINTHEAIRNEUTRAL[PERMAPEDDLE] = 1
LOVEISINTHEAIRNEUTRAL[SHAFTED] = 1
LOVEISINTHEAIRNEUTRAL[SWEETTOOTH] = 1
LOVEISINTHEAIRNEUTRAL[THEROCKETSPINKGLARE] = 1
LOVEISINTHEAIRNEUTRAL[TOUGHLOVE] = 80
LOVEISINTHEAIRNEUTRAL[FOOLFORLOVE] = 80


FLIRTWITHDISASTERA=1279
NATIONOFADORATIONA=1697


LOVEISINTHEAIRALLIANCE = {}
LOVEISINTHEAIRALLIANCE[FLIRTWITHDISASTERA] = 1
LOVEISINTHEAIRALLIANCE[NATIONOFADORATIONA] = 1


FLIRTWITHDISASTERH=1280
NATIONOFADORATIONH=1698


LOVEISINTHEAIRHORDE = {}
LOVEISINTHEAIRHORDE[FLIRTWITHDISASTERH] = 1
LOVEISINTHEAIRHORDE[NATIONOFADORATIONH] = 1

--darkmoon--

BLASTENHEIMER=6021
COMEONECOMEALL=6019
DARKMOONDEFENDER=6028
DARKMOONDESPOILER=6029
DARKMOONDOMINATOR=6024
DARKMOONDUELIST=6023
DARKMOONDUNGEONEER=6027
FAIREFAVORS=6032
FAIRGOERSFEAST=6026
IWASPROMISEDAPONY=6025
QUICKSHOT=6022
STEPRIGHTUP=6020
TAKINGTHESHOWONTHEROADA=6030
TAKINGTHESHOWONTHEROADH=6031
FLYINGHIGH=9250
THATRABBITSDYNAMITE=6332
ACETONKCOMMANDER=9885
TRIUMPHANTTURTLETOSSING=9894
THATSWHACK=9983
DARKMOONRACEENTHUSIAST=9755
DARKMOONRACERNOVICE=9756
BLASTOFF=9770
WAYFARER=9786
GOGETTER=9780
BIGRACEENTHUSIAST=9793
ROCKETMAN=9800
VAGABOND=9806
GOALORIENTED=9812
DARKMOONLIKETHEWIND=9819
RINGMASTER=9251
POWERMONGERBRONZE =9781
DARKMOONRACERLEADFOOT=9760
DARKMOONRACERJOCKEY=9759
POWERMONGERSILVER=9783
POWERMONGERGOLD=9785
WANDERLUSTERSILVER=9790
WANDERLUSTERGOLD=9792
WANDERLUSTERBRONZE=9787

DARKMOONFAIRENEUTRAL = {}
DARKMOONFAIRENEUTRAL[COMEONECOMEALL] = 1
DARKMOONFAIRENEUTRAL[QUICKSHOT] = 1
DARKMOONFAIRENEUTRAL[STEPRIGHTUP] = 1
DARKMOONFAIRENEUTRAL[BLASTENHEIMER] = 1
DARKMOONFAIRENEUTRAL[IWASPROMISEDAPONY] = 20
DARKMOONFAIRENEUTRAL[FAIREFAVORS] =20  
--faire favors works at any level, but 75 skill is needed, +archy
DARKMOONFAIRENEUTRAL[DARKMOONDEFENDER] = 30
DARKMOONFAIRENEUTRAL[FAIRGOERSFEAST] = 85
DARKMOONFAIRENEUTRAL[DARKMOONDESPOILER] = 85
DARKMOONFAIRENEUTRAL[DARKMOONDUNGEONEER] = 85
DARKMOONFAIRENEUTRAL[FLYINGHIGH] = 1
DARKMOONFAIRENEUTRAL[THATRABBITSDYNAMITE] = 80
DARKMOONFAIRENEUTRAL[ACETONKCOMMANDER] = 1
DARKMOONFAIRENEUTRAL[TRIUMPHANTTURTLETOSSING] = 1
DARKMOONFAIRENEUTRAL[THATSWHACK] = 1
DARKMOONFAIRENEUTRAL[DARKMOONRACEENTHUSIAST] = 1
DARKMOONFAIRENEUTRAL[DARKMOONRACERNOVICE] = 1
DARKMOONFAIRENEUTRAL[BLASTOFF] = 1
DARKMOONFAIRENEUTRAL[WAYFARER] = 1
DARKMOONFAIRENEUTRAL[RINGMASTER] = 1
DARKMOONFAIRENEUTRAL[GOGETTER] = 1
DARKMOONFAIRENEUTRAL[BIGRACEENTHUSIAST] = 1
DARKMOONFAIRENEUTRAL[ROCKETMAN] = 1
DARKMOONFAIRENEUTRAL[VAGABOND] = 1
DARKMOONFAIRENEUTRAL[GOALORIENTED] = 1
DARKMOONFAIRENEUTRAL[DARKMOONLIKETHEWIND] = 1
DARKMOONFAIRENEUTRAL[POWERMONGERBRONZE] = 1
DARKMOONFAIRENEUTRAL[DARKMOONRACERLEADFOOT] = 1
DARKMOONFAIRENEUTRAL[DARKMOONRACERJOCKEY] = 1
DARKMOONFAIRENEUTRAL[WANDERLUSTERBRONZE] = 1
DARKMOONFAIRENEUTRAL[WANDERLUSTERSILVER] = 1
DARKMOONFAIRENEUTRAL[WANDERLUSTERGOLD] = 1
DARKMOONFAIRENEUTRAL[POWERMONGERGOLD] = 1
DARKMOONFAIRENEUTRAL[POWERMONGERSILVER] = 1



--brewfest

STRANGEBREWA=1184
ALMOSTBLINDLUCK=1260
BREWOFTHEMONTH=2796
BREWOFTHEYAR=1183
DIREBREWFEST=295
DISTURBINGHTEPEACE=293
DOESYOURWOLPERTINGERLINGER=1936
DOWNTHEDARKIRON=1186
HAVEKEGWILLTRAVEL=303
BREWFESTDIET=1185
STRANGEBREWH=1203
BREWMASTER=1683


BREWFESTNEUTRAL = {}
BREWFESTNEUTRAL[ALMOSTBLINDLUCK] = 1
BREWFESTNEUTRAL[BREWOFTHEMONTH] = 1
BREWFESTNEUTRAL[BREWOFTHEYAR] = 1
BREWFESTNEUTRAL[DIREBREWFEST] = 89
BREWFESTNEUTRAL[DISTURBINGHTEPEACE] = 60
BREWFESTNEUTRAL[DOESYOURWOLPERTINGERLINGER] = 1
BREWFESTNEUTRAL[DOWNTHEDARKIRON] = 1
BREWFESTNEUTRAL[HAVEKEGWILLTRAVEL] = 1
BREWFESTNEUTRAL[BREWFESTDIET] = 65
BREWFESTNEUTRAL[BREWMASTER] = 65

MERRYMAKER=1691
IRONARMADA=10353

WINTERVEILNEUTRAL = {}
WINTERVEILNEUTRAL[HEKNOWSIFYOUVEBEENNAUGHTY] = 1
WINTERVEILNEUTRAL[WITHALITTLEHELPER] = 10
WINTERVEILNEUTRAL[LETITSNOW] = 10
WINTERVEILNEUTRAL[DANGERZONE] = 10
WINTERVEILNEUTRAL[CRASHINANDTHRASHIN] = 40
WINTERVEILNEUTRAL[ONMETZEN] = 70
WINTERVEILNEUTRAL[SIMPLYABOMINABLE] = 1
WINTERVEILNEUTRAL[TISTHESEASON] = 1
WINTERVEILNEUTRAL[AFROSTYSHAKE] = 1
WINTERVEILNEUTRAL[FALALALAOGRILA] = 1
WINTERVEILNEUTRAL[WINTERVEILGOURMET] = 20
WINTERVEILNEUTRAL[MERRYMAKER] = 70
WINTERVEILNEUTRAL[IRONARMADA] = 1

--DAY OF THE DEAD
CALAVERA=9428
DEADMANSPARTY=3456
TOTHEAFTERLIFE=9426
VIENTOS=9427

DAYOFTHEDEADACHS = {}
DAYOFTHEDEADACHS [CALAVERA] = 1
DAYOFTHEDEADACHS [DEADMANSPARTY] = 1
DAYOFTHEDEADACHS [TOTHEAFTERLIFE] = 1
DAYOFTHEDEADACHS [VIENTOS] = 1

--PIRATESDAY
CAPTAINSBOOTY= 3457
PIRATESDAYACHS = {}
PIRATESDAYACHS[CAPTAINSBOOTY] = 1

