TERROKARZONE = "Terrokar Forest"

--bcrep
BURNINGCRUSADERH=763
BURNINGCRUSADERA=764
CENARIONWARHIPPOGRYPH=893
FLYINGHIGHOVERSKETTIS=894
AQUESTADAYKEEPSTHEOGRESATBAY=896
YOURESOOFFENSIVE=897
ONWINGSOFNETHER=898
MAGHAROFDRAENOR=901
OHMYKURENAI=899
CHIEFEXALTEDOFFICER=902
CZAROFSPOREGGAR=900
SHATTRATHDIVIDED=903
SWORNTOTHEDWEATHSWORN=958
SCALEOFTHESANDS=959
VIOLETEYE=960
SKYSHATTERED=1638


OUTLANDREPACHS = {}
OUTLANDREPACHS[CENARIONWARHIPPOGRYPH] = 65
OUTLANDREPACHS[FLYINGHIGHOVERSKETTIS] = 65
OUTLANDREPACHS[AQUESTADAYKEEPSTHEOGRESATBAY] = 65
OUTLANDREPACHS[YOURESOOFFENSIVE] = 65
OUTLANDREPACHS[ONWINGSOFNETHER] = 65
OUTLANDREPACHS[MAGHAROFDRAENOR] = 65
OUTLANDREPACHS[CHIEFEXALTEDOFFICER] = 65
OUTLANDREPACHS[CZAROFSPOREGGAR] = 65
OUTLANDREPACHS[SHATTRATHDIVIDED] = 65
OUTLANDREPACHS[SWORNTOTHEDWEATHSWORN] = 65
OUTLANDREPACHS[SCALEOFTHESANDS] = 65
OUTLANDREPACHS[VIOLETEYE] = 65
OUTLANDREPACHS[SKYSHATTERED] = 65



HELLFIREPENINSULA=862 --explore
TERROKARFOREST=867
BLADESEDGEMOUNTAINS=865
SHADOWMOONVALLEY=864
ZANGARMARSH=863
NAGRAND=866
NETHERSTORM=843
MEDIUMRARE=1311
BLOODYRARE=1312

TERROROFTEROKKARH = 1272
NAGRANDSLAMH = 1273
LOREMASTEROFOUTLAND =1262 
TOHELLFIREANDBACKA = 1189
TERROROFTEROKKARA= 1191
NAGRANDSLAMA = 1192
TOHELLFIREANDBACKH = 1271
EXPLOREOUTLAND =44



BLADESEDGEBOMBERMAN=1276
BOMBSAWAY=1275
HILLSLIKEWHITEELEKK=939


--bc
ZONEQUESTS[BLADESEDGEMOUNTAINS]= 1193
ZONEQUESTS[SHADOWMOONVALLEY]= 1195
ZONEQUESTS[ZANGARMARSH]= 1190
ZONEQUESTS[NETHERSTORM]= 1194



LURKERABOVE=144
BLACKTEMPLE=697
BATTLEFORMOUNTHYJAL=695
KARAZHAN=690
GRUULSLAIR=692
MAGTHERIDONSLAIR=693
SERPENTSHRINECAVERN=694
TEMPESTKEEP=696
SUNWELLPLATEAU=698
--outland raids
ASHESOFALAR=885
THORIDAL=725
OUTLANDRAIDER=1286


OUTLANDACHS = {}
OUTLANDACHS[BLADESEDGEMOUNTAINS] = 63
OUTLANDACHS[ZONEQUESTS[BLADESEDGEMOUNTAINS]] = 63
OUTLANDACHS[BLADESEDGEBOMBERMAN] = 63
OUTLANDACHS[SHADOWMOONVALLEY] = 65
OUTLANDACHS[ZONEQUESTS[SHADOWMOONVALLEY]] = 65
OUTLANDACHS[ZANGARMARSH] = 61
OUTLANDACHS[ZONEQUESTS[ZANGARMARSH]] = 61
OUTLANDACHS[HILLSLIKEWHITEELEKK] = 62
OUTLANDACHS[NETHERSTORM] = 65
OUTLANDACHS[ZONEQUESTS[NETHERSTORM]] = 65
OUTLANDACHS[LOREMASTEROFOUTLAND] =65
OUTLANDACHS[WARGLAIVESOFAZZINOTH]=70
OUTLANDACHS[OHMYKURENAI]=70 --NAGRAND
OUTLANDACHS[EXPLOREOUTLAND] = 70
OUTLANDACHS[HEROOFSHATTRATH] = 65
OUTLANDACHS[GUARDIANOFCENARIUS] = 70 --also needs vanilla section
OUTLANDACHS[LURKERABOVE] = 70 -- 144
OUTLANDACHS[SUNWELLPLATEAU] = 70
OUTLANDACHS[BLACKTEMPLE] = 70
OUTLANDACHS[BATTLEFORMOUNTHYJAL] = 70
OUTLANDACHS[KARAZHAN] = 70
OUTLANDACHS[GRUULSLAIR] = 70
OUTLANDACHS[MAGTHERIDONSLAIR] = 70
OUTLANDACHS[SERPENTSHRINECAVERN] = 70
OUTLANDACHS[TEMPESTKEEP] = 70
OUTLANDACHS[OUTLANDRAIDER] = 70
OUTLANDACHS[ASHESOFALAR] = 70
OUTLANDACHS[THORIDAL] = 70
OUTLANDACHS[HELLFIREPENINSULA] = 58
OUTLANDACHS[NAGRAND] = 61

--terrokar
TERROKARACHS = {}
TERROKARACHS[BOMBSAWAY] = 62
TERROKARACHS[TERROKARFOREST] = 61


OUTLANDALLIANCEACHS = {}
OUTLANDALLIANCEACHS [TOHELLFIREANDBACKA] = 58
OUTLANDALLIANCEACHS [TERROROFTEROKKARA] = 61
OUTLANDALLIANCEACHS [NAGRANDSLAMA] = 62
OUTLANDALLIANCEACHS [BURNINGCRUSADERA]=70
OUTLANDHORDEACHS = {}
OUTLANDHORDEACHS  [TOHELLFIREANDBACKH] = 58
OUTLANDHORDEACHS  [TERROROFTEROKKARH] = 61
OUTLANDHORDEACHS  [NAGRANDSLAMH] = 62
OUTLANDHORDEACHS [BURNINGCRUSADERH]=70
