AWORTHYOPPONENT=7437
BALLADOFLIULANG=6856
BETWEENASAUROKANDAHARDPLACE=6716
BOUNTYOFPANDARIA=7996
CHAMPIONSOFLEISHEN=8103
COULDWEFINDMORELIKETHAT=7438
EXPLOREDREADWASTES=6978
EXPLOREJADEFFOREST=6351
EXPLOREKRASARANGWILDS=6975
EXPLOREKUNLAISUMMIT=6976
EXPLORETOWNLONGSTEPPES=6977
EXPLOREVALEOFETERNALBLOSSOMS=6979
EXPLOREVALLEYOFTHEFOURWINDS=6969
EXTREMETREASUREHUNTER=8726
EYESONTHEGROUND=8725
FINDERSKEEPERS=7282
FISHTALES=6846
FORTUNEOFPANDARIA=7995
GLORIOUS=7439
GODSANDMONSTERS=8051
GOINGTONEEDABIGGERBAG=8728
HEARTOFTHEMANTIDSWARM=6857
HOZENINTHEMIST=6850
IMINYOURBASEKILLINGYOURDUDES=7932
ISANOTHERMANSTREASURE=7284
KILLINGTIME=8712
LEGENDOFTHEBREWFATHERS=7230
LEGENDOFTHEPAST=8723
LOSTANDFOUND=7281
ONEMANSTRASH=7283
PILGRIMAGE=8724
RESTOREBALANCE=7381
RICHESOFPANDARIA=7997
ROLOSRIDDLE=8730
RUMBLESOFTHUNDER=8050
DARKHEARTOFTHEMOGU=6754
SEVENBURDENSOFSHAOHAO=6855
SONGOFTHEYAUNGOL=6847
ZANDALARIPROPHECY=8049
TIMELESSCHAMPION=8714
TIMELESSLEGENDS=8784
TIMELESSNUTRIMENT=8722
TREASUREOFPANDARIA=7994
TREASURETREASUREEVERYWHERE=8729
WANDERERSDREAMERSANDYOU=7518
WHATISWORTHFIGHTINGFOR=6858
WHERETHERESPIRATESTHERESBOOTY=8727
ZARHYMALTOGETHER=8743
ZULAGAIN=8078

--quests
ATASTEOFTHINGSTOCOME=7294
AINTLOSTNOMORE=7296
AMBERISTHECOLOROFMYENEMY=7312
ATASTEOFHISTORY=7318
ATESTOFVALOR=8030
CHAMPIONOFCHIJI=7287
COLLATERALDAMAGE=7323
BLUERESPONSE=8112
BOOP=8118
CHAPTERI=7533
CHAPTERII=7534
CHAPTERIII=7535
CHAPTERIV=7536
CHAPTERV=8325
DREADHASTEMAKESDREADWASTE=6540
EVERYDAYIMPANDAREN=7285
FINISHTHEM=7286
FIREINTHEYAUNGHOLE=7309
DEFENDEROFGODS=7310
DOGPILE=7320
DIREHORNINACHINASHOP=8120
HOWTOSTRAINYOURDRAGON=7290
INATRAILOFSMOKE=7291
GREENACRES=7292
LISTENTOTHEDRUNKFISH=7295
GETTINGAROUNDWITHTHESHADOPAN=7298
KNOWYOURROLE=7308
ISLEOFTHUNDER=8099
INTHEHALLOFTHETHUNDERKING=8106
FORTHEWARD=8117



MIGHTYROAMINKRASARANGER=6535
ONESTEPPEFORWARDTWOSTEPPESBACK=6539
LOREMASTEROFPANDARIA=6541
LONERANDAREBEL=7299
OVERTHEIRHEADS=7316
ONEMANYARMY=7317
ONESTEPATATIME=7324
OPERATIONSHIELDWALLCAMPAIGN=7928
OURPOWERSCOMBINED=8119
RALLYTHEVALLEY=6301
SLUMITINTHESUMMIT=6537
SHADOWHOPPER=7289
PROVENSTRENGTH=7297
SILENTASSASSIN=7307
READYFORRAIDINGIII=7319
SAVIOROFSTONEPLOW=7502
ROLLCLUB=7322
PAYTOSLAY=8100
READYFORRAAAIDDD=8107
PLATFORMHERO=8114


UPJADECOMPLETE=6300
YAKATTACK=7288
TILLTHEBREAKOFDAWN=7293
STAYKLAXXI=7313
TESTDRIVE=7314
SPREADINGTHEWARMTH=7321
THUNDERPLUNDER=8104
CRUMBLEBUNDLE=8105
WHENINIHGALUKDOASTHESKUMBLADEDO=8108
THEMOGUBELOWGU=8109
THISISNTEVENMYFINALFORM=8111
SPEEDMETAL=8115
YOUMADEMEBLEEDMYOWNBLOOD=8116
ZANDALARILIBRARYCARD=8212
STORMBREAKER=8121
EXPLOREPANDARIA=6974

PANDARIAACHS = {}
PANDARIAACHS[AWORTHYOPPONENT] = 89
PANDARIAACHS[BALLADOFLIULANG] = 90
PANDARIAACHS[BETWEENASAUROKANDAHARDPLACE] = 85
PANDARIAACHS[BOUNTYOFPANDARIA] = 85
PANDARIAACHS[CHAMPIONSOFLEISHEN] = 85
PANDARIAACHS[COULDWEFINDMORELIKETHAT] = 89
PANDARIAACHS[EXPLOREDREADWASTES] = 85
PANDARIAACHS[EXPLOREJADEFFOREST] = 85
PANDARIAACHS[EXPLOREKRASARANGWILDS] = 85
PANDARIAACHS[EXPLOREKUNLAISUMMIT] = 85
PANDARIAACHS[EXPLORETOWNLONGSTEPPES] = 85
PANDARIAACHS[EXPLOREVALEOFETERNALBLOSSOMS] = 85
PANDARIAACHS[EXPLOREVALLEYOFTHEFOURWINDS] = 85
PANDARIAACHS[EXTREMETREASUREHUNTER] = 89
PANDARIAACHS[EYESONTHEGROUND] = 89
PANDARIAACHS[FINDERSKEEPERS] = 85
PANDARIAACHS[FISHTALES] = 85
PANDARIAACHS[FORTUNEOFPANDARIA] = 85
PANDARIAACHS[GLORIOUS] = 89
PANDARIAACHS[GOINGTONEEDABIGGERBAG] = 90
PANDARIAACHS[HOZENINTHEMIST] = 85
PANDARIAACHS[ISANOTHERMANSTREASURE] = 85
PANDARIAACHS[KILLINGTIME] = 89
PANDARIAACHS[LEGENDOFTHEBREWFATHERS] = 85
PANDARIAACHS[LEGENDOFTHEPAST] = 89
PANDARIAACHS[LOSTANDFOUND] = 85
PANDARIAACHS[ONEMANSTRASH] = 85
PANDARIAACHS[PILGRIMAGE] = 89
PANDARIAACHS[RESTOREBALANCE] = 85
PANDARIAACHS[RICHESOFPANDARIA] = 89
PANDARIAACHS[ROLOSRIDDLE] = 89
PANDARIAACHS[DARKHEARTOFTHEMOGU] = 89
PANDARIAACHS[SEVENBURDENSOFSHAOHAO] = 90
PANDARIAACHS[SONGOFTHEYAUNGOL] = 85
PANDARIAACHS[TIMELESSCHAMPION] = 90
PANDARIAACHS[TIMELESSLEGENDS] = 85
PANDARIAACHS[TIMELESSNUTRIMENT] = 89
PANDARIAACHS[TREASUREOFPANDARIA] = 85
PANDARIAACHS[TREASURETREASUREEVERYWHERE] = 85
PANDARIAACHS[WANDERERSDREAMERSANDYOU] = 89
PANDARIAACHS[WHATISWORTHFIGHTINGFOR] = 90
PANDARIAACHS[WHERETHERESPIRATESTHERESBOOTY] = 89
PANDARIAACHS[ZARHYMALTOGETHER] = 90
PANDARIAACHS[ZULAGAIN] = 85

PANDARIAACHS[UPJADECOMPLETE] = 85
PANDARIAACHS[RALLYTHEVALLEY] = 85
PANDARIAACHS[MIGHTYROAMINKRASARANGER] = 85
PANDARIAACHS[SLUMITINTHESUMMIT] = 89
PANDARIAACHS[ONESTEPPEFORWARDTWOSTEPPESBACK] = 89
PANDARIAACHS[DREADHASTEMAKESDREADWASTE] = 89
PANDARIAACHS[LOREMASTEROFPANDARIA] = 90
PANDARIAACHS[EVERYDAYIMPANDAREN] = 85
PANDARIAACHS[FINISHTHEM] = 85
PANDARIAACHS[CHAMPIONOFCHIJI] = 85
PANDARIAACHS[YAKATTACK] = 89
PANDARIAACHS[SHADOWHOPPER] = 85
PANDARIAACHS[HOWTOSTRAINYOURDRAGON] = 85
PANDARIAACHS[INATRAILOFSMOKE] = 85
PANDARIAACHS[GREENACRES] = 85
PANDARIAACHS[TILLTHEBREAKOFDAWN] = 85
PANDARIAACHS[ATASTEOFTHINGSTOCOME] = 85
PANDARIAACHS[LISTENTOTHEDRUNKFISH] = 85
PANDARIAACHS[AINTLOSTNOMORE] = 85
PANDARIAACHS[PROVENSTRENGTH] = 85
PANDARIAACHS[GETTINGAROUNDWITHTHESHADOPAN] = 90
PANDARIAACHS[LONERANDAREBEL] = 85
PANDARIAACHS[SILENTASSASSIN] = 89
PANDARIAACHS[KNOWYOURROLE] = 89
PANDARIAACHS[FIREINTHEYAUNGHOLE] = 85
PANDARIAACHS[DEFENDEROFGODS] = 85
PANDARIAACHS[AMBERISTHECOLOROFMYENEMY] = 85
PANDARIAACHS[STAYKLAXXI] = 89
PANDARIAACHS[TESTDRIVE] = 85
PANDARIAACHS[OVERTHEIRHEADS] = 85
PANDARIAACHS[ONEMANYARMY] = 85
PANDARIAACHS[ATASTEOFHISTORY] = 85
PANDARIAACHS[READYFORRAIDINGIII] = 89
PANDARIAACHS[DOGPILE] = 89
PANDARIAACHS[SPREADINGTHEWARMTH] = 89
PANDARIAACHS[SAVIOROFSTONEPLOW] = 89
PANDARIAACHS[ROLLCLUB] = 89
PANDARIAACHS[COLLATERALDAMAGE] = 89
PANDARIAACHS[ONESTEPATATIME] = 89
PANDARIAACHS[OPERATIONSHIELDWALLCAMPAIGN] = 85
PANDARIAACHS[ISLEOFTHUNDER] = 85
PANDARIAACHS[PAYTOSLAY] = 85
PANDARIAACHS[THUNDERPLUNDER] = 85
PANDARIAACHS[CRUMBLEBUNDLE] = 85
PANDARIAACHS[INTHEHALLOFTHETHUNDERKING] = 85
PANDARIAACHS[READYFORRAAAIDDD] = 85
PANDARIAACHS[WHENINIHGALUKDOASTHESKUMBLADEDO] = 85
PANDARIAACHS[THEMOGUBELOWGU] = 85
PANDARIAACHS[THISISNTEVENMYFINALFORM] = 85
PANDARIAACHS[BLUERESPONSE] = 89
PANDARIAACHS[PLATFORMHERO] = 85
PANDARIAACHS[SPEEDMETAL] = 85
PANDARIAACHS[YOUMADEMEBLEEDMYOWNBLOOD] = 89
PANDARIAACHS[FORTHEWARD] = 89
PANDARIAACHS[BOOP] = 89
PANDARIAACHS[OURPOWERSCOMBINED] = 89
PANDARIAACHS[DIREHORNINACHINASHOP] = 89
PANDARIAACHS[ZANDALARILIBRARYCARD] = 89
PANDARIAACHS[STORMBREAKER] = 89
PANDARIAACHS[CHAPTERI] = 88
PANDARIAACHS[CHAPTERII] = 89
PANDARIAACHS[CHAPTERIII] = 89
PANDARIAACHS[CHAPTERIV] = 89
PANDARIAACHS[CHAPTERV] = 89
PANDARIAACHS[ATESTOFVALOR] = 89
PANDARIAACHS[EXPLOREPANDARIA] = 90


MIGHTYROAMINKRASARANGERA=6535
OPERATIONSHIELDWALLCAMPAIGN=7928
SLUMITINTHESUMMITA=6537
UPJADECOMPLETEA=6300

PANDARIAACHSALLY = {}

PANDARIAACHSALLY [MIGHTYROAMINKRASARANGERA] = 85
PANDARIAACHSALLY [OPERATIONSHIELDWALLCAMPAIGN] = 85
PANDARIAACHSALLY [SLUMITINTHESUMMITA] = 85
PANDARIAACHSALLY [UPJADECOMPLETEA] = 85




MIGHTYROAMINKRASARANGERH=6536
DOMINANCEOFFENSIVECAMPAIGN=7929
SLUMITINTHESUMMITH=6538
UPJADECOMPLETEH=6534

PANDARIAACHSHORDE = {}
PANDARIAACHSHORDE [MIGHTYROAMINKRASARANGERH] = 85
PANDARIAACHSHORDE [DOMINANCEOFFENSIVECAMPAIGN] = 85
PANDARIAACHSHORDE [SLUMITINTHESUMMITH] = 85
PANDARIAACHSHORDE [UPJADECOMPLETEH] = 85

--KRASANG(SP?)
PANDARIAACHS[IMINYOURBASEKILLINGYOURDUDES] = 85

--timeless isle
TIMELESSISLEACHS = {}
TIMELESSISLEACHS[GODSANDMONSTERS] = 90 --timeless isle

--ISLE OF THUNDER
PANDARIAACHS[RUMBLESOFTHUNDER] = 90 
PANDARIAACHS[ZANDALARIPROPHECY] = 90 

--DREAD WASTES
PANDARIAACHS[HEARTOFTHEMANTIDSWARM] = 89

QUEUEINGSPREE = 6943
--panda scenarios (neutral)
ABREWINGSTORM=7252
ALITTLEPATIENCE=7988
ACCELERATEDARCHAEOLOGY=8319
ARENAOFANNIHILATION=7271
ASSAULTONZANVESS=8016
BEATTHEHEAT=7273
BINANVILLAGEALLSTAR=6931
BLODINTHESNOW=8316
BREWMOONFESTIVAL=6923
BUBBLETRAPPED=7989
CANNONBALLER=7990
CRYPTOFFORGOTTENKINGS=7522
DAGGERINTHEDARK=8009
DARKHEARTOFPANDARIA=8317
DONTSHAKETHEKEG=7257
FANCYFOOTWORK=7276
FIGHTANGERWITHANGER=8368
FORTHESWARM=8017
GREENSTONEVILLAGE=7265
HEEDTHEWEED=8329
HEKIMASHEALHALTER=8330
HCABREWINGSTORM=8310
HCBLOODINTHESNOW=8312
HCCRYPTOFFORGOTTENKINGS=8311
HCDARKHEARTOFPANDARIA=8318
HCSECRETSOFRAGEFIRE=8327
IUSEDTOLOVETHEM=7992
INTHEEYEOFTHETIGER=7272
ITSATRAP=7275
KEEPTHOSEBOMBSAWAY=8347
MONKEYINTHEMIDDLE=7239
MONKEYSEEMONKEYKILL=7248
NOEGGLEFTBEHIND=7987
PARTYOFSIX=7258
PERFECTDELIVERY=7267
PUBCRAWL=7385
SAVEITFORLATER=7266
SPILLNOEVIL=7231
FEWPROUDANDGOBSQUAD=8295
KEGRUNNER=7232
PERFECTPOUR=7261
SECRETSOFRAGEFIRE=8294
UNGAINGOO=7249
WATERYGRAVE=7984
WEVEBEENDANCIN=7993
WHICHCAMEFIRST=7991
YAUNGOLIANBARBECUE=6930
YOUMEANTHATWASNTAVOIDZONE=7986
QUEUEINGSPREE=6943

PANDARIASCENARIOS = {}

PANDARIASCENARIOS[ABREWINGSTORM]=89
PANDARIASCENARIOS[ALITTLEPATIENCE]=89
PANDARIASCENARIOS[ACCELERATEDARCHAEOLOGY]=89
PANDARIASCENARIOS[ARENAOFANNIHILATION]=89
PANDARIASCENARIOS[ASSAULTONZANVESS]=89
PANDARIASCENARIOS[BEATTHEHEAT]=89
PANDARIASCENARIOS[BINANVILLAGEALLSTAR]=89
PANDARIASCENARIOS[BLODINTHESNOW]=89
PANDARIASCENARIOS[BREWMOONFESTIVAL]=89
PANDARIASCENARIOS[BUBBLETRAPPED]=89
PANDARIASCENARIOS[CANNONBALLER]=89
PANDARIASCENARIOS[CRYPTOFFORGOTTENKINGS]=89
PANDARIASCENARIOS[DAGGERINTHEDARK]=89
PANDARIASCENARIOS[DARKHEARTOFPANDARIA]=89
PANDARIASCENARIOS[DONTSHAKETHEKEG]=89
PANDARIASCENARIOS[FANCYFOOTWORK]=89
PANDARIASCENARIOS[FIGHTANGERWITHANGER]=89
PANDARIASCENARIOS[FORTHESWARM]=89
PANDARIASCENARIOS[GREENSTONEVILLAGE]=89
PANDARIASCENARIOS[HEEDTHEWEED]=89
PANDARIASCENARIOS[HEKIMASHEALHALTER]=89
PANDARIASCENARIOS[HCABREWINGSTORM]=89
PANDARIASCENARIOS[HCBLOODINTHESNOW]=89
PANDARIASCENARIOS[HCCRYPTOFFORGOTTENKINGS]=89
PANDARIASCENARIOS[HCDARKHEARTOFPANDARIA]=89
PANDARIASCENARIOS[HCSECRETSOFRAGEFIRE]=89
PANDARIASCENARIOS[IUSEDTOLOVETHEM]=89
PANDARIASCENARIOS[INTHEEYEOFTHETIGER]=89
PANDARIASCENARIOS[ITSATRAP]=89
PANDARIASCENARIOS[KEEPTHOSEBOMBSAWAY]=89
PANDARIASCENARIOS[MONKEYINTHEMIDDLE]=89
PANDARIASCENARIOS[MONKEYSEEMONKEYKILL]=89
PANDARIASCENARIOS[NOEGGLEFTBEHIND]=89
PANDARIASCENARIOS[PARTYOFSIX]=89
PANDARIASCENARIOS[PERFECTDELIVERY]=89
PANDARIASCENARIOS[PUBCRAWL]=89
PANDARIASCENARIOS[SAVEITFORLATER]=89
PANDARIASCENARIOS[SPILLNOEVIL]=89
PANDARIASCENARIOS[FEWPROUDANDGOBSQUAD]=89
PANDARIASCENARIOS[KEGRUNNER]=89
PANDARIASCENARIOS[PERFECTPOUR]=89
PANDARIASCENARIOS[SECRETSOFRAGEFIRE]=89
PANDARIASCENARIOS[UNGAINGOO]=89
PANDARIASCENARIOS[WATERYGRAVE]=89
PANDARIASCENARIOS[WEVEBEENDANCIN]=89
PANDARIASCENARIOS[WHICHCAMEFIRST]=89
PANDARIASCENARIOS[YAUNGOLIANBARBECUE]=89
PANDARIASCENARIOS[YOUMEANTHATWASNTAVOIDZONE]=89
PANDARIASCENARIOS[QUEUEINGSPREE]=89

BATTLEONTHEHIGHSEASA=8314
HEROICBATTTLEONTHEHIGHSEASA=8364
KITEFIGHTA=7526
LIONSLANDING=8010
NOTANKYOUA=7527
NUMBERFIVEISALIVEA=8011
SCENATURDAYA=6874
THERAMORESFALLA=7523
WASTENOTWANTNOTA=8012


PANDARIAALLYSCENARIOS = {}


PANDARIAALLYSCENARIOS [BATTLEONTHEHIGHSEASA] = 85
PANDARIAALLYSCENARIOS [HEROICBATTTLEONTHEHIGHSEASA] = 85
PANDARIAALLYSCENARIOS [KITEFIGHTA] = 85
PANDARIAALLYSCENARIOS [LIONSLANDING] = 85
PANDARIAALLYSCENARIOS [NOTANKYOUA] = 85
PANDARIAALLYSCENARIOS [NUMBERFIVEISALIVEA] = 85
PANDARIAALLYSCENARIOS [SCENATURDAYA] = 85
PANDARIAALLYSCENARIOS [THERAMORESFALLA] = 85
PANDARIAALLYSCENARIOS [WASTENOTWANTNOTA] = 85



BATTLEONTHEHIGHSEASH=8315
DOMINATIONPOINT=8013
HEROICBATTTLEONTHEHIGHSEASH=8366
KITEFIGHTH=7529
NOTANKYOUH=7530
NUMBERFIVEISALIVEH=8014
SCENATURDAYH=7509
THERAMORESFALLH=7524
WASTENOTWANTNOTH=8015

PANDARIAHORDESCENARIOS = {}

PANDARIAHORDESCENARIOS[BATTLEONTHEHIGHSEASH] = 85
PANDARIAHORDESCENARIOS[DOMINATIONPOINT] = 85
PANDARIAHORDESCENARIOS[HEROICBATTTLEONTHEHIGHSEASH] = 85
PANDARIAHORDESCENARIOS[KITEFIGHTH] = 85
PANDARIAHORDESCENARIOS[NOTANKYOUH] = 85
PANDARIAHORDESCENARIOS[NUMBERFIVEISALIVEH] = 85
PANDARIAHORDESCENARIOS[SCENATURDAYH] = 85
PANDARIAHORDESCENARIOS[THERAMORESFALLH] = 85
PANDARIAHORDESCENARIOS[WASTENOTWANTNOTH] = 85



--PANDA REP

EMPERORSHAOHAO=8715
FRIENDONTHEFARM=6551
FRIENDSONTHEFARM=6552
KLAXXI=6545
ORDEROFTHECLOUDSERPENT=6550
SHADOPAN=6366
SHADOPANASSAULT=8210
ANGLERS=6547
AUGUSTCELESTIALS=6543
GOLDENLOTUS=6546
LOREWALKERS=6548
SHADOMASTER=7479
TILLERS=6544
WAKENER=8023

PANDARIAREP ={}
PANDARIAREP[EMPERORSHAOHAO]=85
PANDARIAREP[FRIENDONTHEFARM]=85
PANDARIAREP[FRIENDSONTHEFARM]=85
PANDARIAREP[KLAXXI]=85
PANDARIAREP[ORDEROFTHECLOUDSERPENT]=85
PANDARIAREP[SHADOPAN]=85
PANDARIAREP[SHADOPANASSAULT]=85
PANDARIAREP[ANGLERS]=85
PANDARIAREP[AUGUSTCELESTIALS]=85
PANDARIAREP[GOLDENLOTUS]=85
PANDARIAREP[LOREWALKERS]=85
PANDARIAREP[SHADOMASTER]=85
PANDARIAREP[TILLERS]=85
PANDARIAREP[WAKENER]=85

--ally rep
KIRINTOROFFENSIVE=8208
OPERATIONSHIELDWALL=8205
PANDARENAMBASSADORA=6828

PANDARIAREPALLY = {}
PANDARIAREPALLY [KIRINTOROFFENSIVE] = 85
PANDARIAREPALLY [OPERATIONSHIELDWALL] = 85
PANDARIAREPALLY [PANDARENAMBASSADORA] = 85

--horde rep
DOMINANCEOFFENSIVE=8206
SUNREAVERONSLAUGHT=8209
PANDARENAMBASSADORH=6827

PANDARIAREPHORDE = {}
PANDARIAREPHORDE[DOMINANCEOFFENSIVE] = 85
PANDARIAREPHORDE[SUNREAVERONSLAUGHT] = 85
PANDARIAREPHORDE[PANDARENAMBASSADORH] = 85



