
--petbattles(all)
--main
TAMINGTHEWILD=6601
TAMINGEK=6603
TAMINGKALIMDOR=6602
TAMINGOUTLAND=6604
TAMINGCATA=7525
TAMINGPANDARIA=6606
TAMINGAZEROTH=6607
TAMINGNORTHREND= 6605

BATTLEMASTER=7483
FABLEDPANDARENTAMER=8080
ICHOOSEYOU=7908
PANDARENSPIRITTAMER=7936
PETCHARMER=9712
TAMINGDRAENOR=9724
TAMINGTHEGREATOUTDOORS=7498
TAMINGTHEWILD=6601
TAMINGTHEWORLD=7499
THELONGESTDAY=8348
TIMETOOPENAPETSTORE=7521
TRAINEREXTRAORDINAIRE=7482
ULTIMATETRAINER=6600

--15118 COLLECT PETS
HIGHQUALITY=7463
LITTLESTPETSHOP=5875
MASTERPETHUNTER=6557
THATWASCLOSE=6571
ANUNCOMMONFIND=7465
GOINGTONEEDMORELEASHES=7500
ZENPETHUNTER=7436
QUALITYANDQUANTITY=7464
FAMILYREUNION=6608
EKTAMER=6613
KALIMDORTAMER=6612
OUTLANDTAMER=6614
NORTHRENDTAMER=6615
PANDARIATAMER=6616
CONTINENTALTAMER=6611
EKSAFARI=6586
KALIMDORSAFARI=6585
OUTLANDSAFARI=6587
NORTHRENDSAFARI=6588
PANDARIASAFARI=6589
DRAENORSAFARI=9685
WORLDSAFARI=6590
CELESTIALFAMILY=8519
CRAZYFORCATS=8397
RAIDINGWITHLEASHES=7934
RAIDINGWITHLEASHESII=8293
RAIDINGWITHLEASHESIII=9824

COLLECTPETACHS = {}
COLLECTPETACHS[HIGHQUALITY] =1
COLLECTPETACHS[LITTLESTPETSHOP] =1
COLLECTPETACHS[MASTERPETHUNTER] =1
COLLECTPETACHS[THATWASCLOSE] =1
COLLECTPETACHS[ANUNCOMMONFIND] =1
COLLECTPETACHS[GOINGTONEEDMORELEASHES] =1
COLLECTPETACHS[ZENPETHUNTER] =1
COLLECTPETACHS[QUALITYANDQUANTITY] =1
COLLECTPETACHS[FAMILYREUNION] =1
COLLECTPETACHS[EKTAMER] =40
COLLECTPETACHS[KALIMDORTAMER] =60
COLLECTPETACHS[OUTLANDTAMER] =60
COLLECTPETACHS[NORTHRENDTAMER] =70
COLLECTPETACHS[PANDARIATAMER] =80
COLLECTPETACHS[CONTINENTALTAMER] =60
COLLECTPETACHS[EKSAFARI] =40
COLLECTPETACHS[KALIMDORSAFARI] =40
COLLECTPETACHS[OUTLANDSAFARI] =60
COLLECTPETACHS[DRAENORSAFARI] =90
COLLECTPETACHS[NORTHRENDSAFARI] =70
COLLECTPETACHS[PANDARIASAFARI] =80
COLLECTPETACHS[WORLDSAFARI] =90
COLLECTPETACHS[CELESTIALFAMILY] =60
COLLECTPETACHS[CRAZYFORCATS] =1
COLLECTPETACHS[RAIDINGWITHLEASHES] =60
COLLECTPETACHS[RAIDINGWITHLEASHESII] =60
COLLECTPETACHS[RAIDINGWITHLEASHESIII] =60

--battling achs
MASTERPETBATTLER=6462
EXPERIENCEDPETBRAWLER=6596
TRAVELINGPETMAULER=6559
TAKEEMALLON=6851
BIGCITYPETBRAWLER=6622
BIGCITYPETBRAWLINHORDE=6621
BIGCITYPETBRAWLINALLIANCE=6584
WINSTREAK=6619
GRANDMASTERPETBATTLER=6591
DRAENICPETBATTLER=9463
MASTERPETBRAWLER=6597
CELESTIALTOURNAMENT=8410
MERCILESSPETBRAWLER=8297
WORLDPETMAULER=6560
NOTIMETOHEAL=6620
MASTEROFTHEMASTERS=8518
ANAWFULLYBIGADVENTURE=9069
TINYTERRORSINTANAAN=10052

BATTLINGPETBATTLEACHS = {}

BATTLINGPETBATTLEACHS[MASTERPETBATTLER] = 1
BATTLINGPETBATTLEACHS[EXPERIENCEDPETBRAWLER] = 1
BATTLINGPETBATTLEACHS[TRAVELINGPETMAULER] = 1
BATTLINGPETBATTLEACHS[TAKEEMALLON] = 1
BATTLINGPETBATTLEACHS[BIGCITYPETBRAWLER] = 1
BATTLINGPETBATTLEACHS[BIGCITYPETBRAWLINHORDE] = 1
BATTLINGPETBATTLEACHS[BIGCITYPETBRAWLINALLIANCE] = 1
BATTLINGPETBATTLEACHS[WINSTREAK] = 1
BATTLINGPETBATTLEACHS[GRANDMASTERPETBATTLER] = 100 --annoying ach that can be directly gone for
BATTLINGPETBATTLEACHS[DRAENICPETBATTLER] = 90
BATTLINGPETBATTLEACHS[MASTERPETBRAWLER] = 1
BATTLINGPETBATTLEACHS[CELESTIALTOURNAMENT] = 60
BATTLINGPETBATTLEACHS[MERCILESSPETBRAWLER] = 1
BATTLINGPETBATTLEACHS[WORLDPETMAULER] = 60
BATTLINGPETBATTLEACHS[NOTIMETOHEAL] = 1
BATTLINGPETBATTLEACHS[MASTEROFTHEMASTERS] = 60
BATTLINGPETBATTLEACHS[ANAWFULLYBIGADVENTURE] = 30
BATTLINGPETBATTLEACHS[TINYTERRORSINTANAAN] = 90

--LEVELLING PETS

ALLGROWNSUP=6570
ALLPETSALLOWED=6610
GROWINGUP=6567
JUSTAPUP=6566
NEWBIE=7433
NOFAVOURITES=6609
OLDTIMER=6569
OVERSTUFFED=9070
PROPETCREW=6581
PROPETGROUP=6578
PROPETMOB=6582
ROOKIEPETCREW=6580
ROOKIEPETGROUP=6579
ROOKIEPETMOB=6583
TIMEFORALEASH=6568


LEVELLINGPETBATTLEACHS ={}
LEVELLINGPETBATTLEACHS[ALLGROWNSUP] =1
LEVELLINGPETBATTLEACHS[ALLPETSALLOWED] =1
LEVELLINGPETBATTLEACHS[GROWINGUP] =1
LEVELLINGPETBATTLEACHS[JUSTAPUP] =1
LEVELLINGPETBATTLEACHS[NEWBIE] =1
LEVELLINGPETBATTLEACHS[NOFAVOURITES] =1
LEVELLINGPETBATTLEACHS[OLDTIMER] =1
LEVELLINGPETBATTLEACHS[OVERSTUFFED] =1
LEVELLINGPETBATTLEACHS[PROPETCREW] =1
LEVELLINGPETBATTLEACHS[PROPETGROUP] =1
LEVELLINGPETBATTLEACHS[PROPETMOB] =1
LEVELLINGPETBATTLEACHS[ROOKIEPETGROUP] =1
LEVELLINGPETBATTLEACHS[ROOKIEPETMOB] =1
LEVELLINGPETBATTLEACHS[TIMEFORALEASH] =1

--professions
PLENTYOFPETS=15




--avg pet level
PETBATTLEACHS = {}
PETBATTLEACHS[TRAINEREXTRAORDINAIRE] = 1
--PETBATTLEACHS[PLENTYOFPETS] = 1
PETBATTLEACHS[TAMINGTHEWILD] = 1
PETBATTLEACHS[TAMINGOUTLAND] = 16
PETBATTLEACHS[TAMINGNORTHREND] = 18
PETBATTLEACHS[TAMINGCATA] = 22
PETBATTLEACHS[TAMINGPANDARIA] = 22
PETBATTLEACHS[TAMINGAZEROTH] = 22
PETBATTLEACHS[BATTLEMASTER] = 1
PETBATTLEACHS[FABLEDPANDARENTAMER] = 10
PETBATTLEACHS[ICHOOSEYOU] = 1
PETBATTLEACHS[PANDARENSPIRITTAMER] = 10
PETBATTLEACHS[PETCHARMER] = 1
PETBATTLEACHS[TAMINGDRAENOR] = 22
PETBATTLEACHS[TAMINGTHEGREATOUTDOORS] = 1
PETBATTLEACHS[TAMINGTHEWILD] = 1
PETBATTLEACHS[TAMINGTHEWORLD] = 1
PETBATTLEACHS[THELONGESTDAY] = 10
PETBATTLEACHS[TIMETOOPENAPETSTORE] = 10
PETBATTLEACHS[TRAINEREXTRAORDINAIRE] = 1
PETBATTLEACHS[ULTIMATETRAINER] = 1


PETBATTLEACHSPLAYER = {}
PETBATTLEACHSPLAYER[TRAINEREXTRAORDINAIRE] = 1
PETBATTLEACHSPLAYER[TAMINGTHEWILD] = 1
PETBATTLEACHSPLAYER[TAMINGOUTLAND] = 60
PETBATTLEACHSPLAYER[TAMINGNORTHREND] = 70
PETBATTLEACHSPLAYER[TAMINGCATA] = 80
PETBATTLEACHSPLAYER[TAMINGPANDARIA] = 80
PETBATTLEACHSPLAYER[TAMINGAZEROTH] = 80
--PETBATTLEACHSPLAYER[PLENTYOFPETS] = 1
PETBATTLEACHSPLAYER[BATTLEMASTER] = 1

PETBATTLEACHSPLAYER[PANDARENSPIRITTAMER] = 80
PETBATTLEACHSPLAYER[FABLEDPANDARENTAMER] = 80
PETBATTLEACHSPLAYER[TAMINGDRAENOR] = 80
PETBATTLEACHSPLAYER[ICHOOSEYOU] = 80

PETBATTLEACHSPLAYER[PETCHARMER] = 80
PETBATTLEACHSPLAYER[TAMINGTHEGREATOUTDOORS] = 1
PETBATTLEACHSPLAYER[TAMINGTHEWILD] = 1
PETBATTLEACHSPLAYER[TAMINGTHEWORLD] = 80
PETBATTLEACHSPLAYER[THELONGESTDAY] = 80
PETBATTLEACHSPLAYER[TIMETOOPENAPETSTORE] = 80
PETBATTLEACHSPLAYER[TRAINEREXTRAORDINAIRE] = 1
PETBATTLEACHSPLAYER[ULTIMATETRAINER] = 80
