WARSONGGULCH1 = "Warsong Lumber Area"


WARSONGGULCH = "Warsong Gulch"
ARATHIBASIN = "Arathi Basin"
EOTS = "Eye of the Storm"
ALTERACVALLEY = "Alterac Valley"
DEEPWINDGORGE = "Deepwind Gorge"
BATTLEFORGILNEAS = "The Battle for Gilneas"
TEMPLEOFKOTMOGU = "Temple of Kotmogu"
SILVERSHARDMINES = "Silvershard Mines"
DEEPWINDGORGE = "Deepwind Gorge"
WINTERGRASP = "Wintergrasp"
TOLBARAD = "Tol Barad"
ARENA = "Arena"
STRANDOFTHEANCIENTS = "Strand of the Ancients"
ISLEOFCONQUEST = "Isle of Conquest"
TWINPEAKS = "Twin Peaks"



--strand of the ancients
ARTILLERYEXPERT=2189
STRANDOFTHEANCIENTSVETERAN=1309
STORMTHEBEACH=1310
STEADYHANDS=1765
DEFENSEOFTHEANCIENTSH=2200
DEFENSEOFTHEANCIENTSA=1757
DAPPERSAPPER=1761
EXPLOSIVESEXPERT=2193
NOTEVENASCRATCHH=2192
NOTEVENASCRATCHA=1762
ARTILLERYVETERAN=1763
DROPIT=1764
DROPITNOW=2190
ANCIENTPROTECTOR=1766
ANCIENTCOURTYARDPROTECTOR=2191
MASTEROFSTRANDOFTHEANCIENTS=2194
STRANDOFTHEANCIENTSVICTORY=1308

--av
SICKLYGAZELLE=223
EVERYTHINGCOUNTS=1164
AVVETERAN=219
ALTERACGRAVEROBBER=221
TOWERDEFENSE=222
LOYALDEFENDER=224
ALTERACBLITZ=226
FROSTWOLFPERFECTION=873
AVALLSTAR=582
FROSTWOLFHOWLER=706
HEROOFFROSTWOLF=708
TOTHELOOTERGOTHESPOILS=1166
MASTEROFAV=1167
EVERYTHINGCOUNTSA=225
LOYALDEFENDERA=1151
STORMPIKEPERFECTION=220
STORMPIKEBATTLECHARGER=707
HEROOFTHESTORMPIKEGUARD=709





--TWIN PEAKS
TWINPEAKSPERFECTION=5215
WILDHAMMERING=5228
TWINPEAKING=5208
TWOTIMER=5210
TOPDEFENDER=5211
SOARINGSPIRITSH=5214
PEAKSPEED=5216
CLOUDNINEH=5227
IMINTHEBLACKLODGE=5220
FIREWALKWITHMEH=5222
TWINPEAKSMOUNTAINEER=5230
DOUBLEJEOPARDYH=5552
MASTEROFTWINPEAKS=5223
CLOUDNINEA=5226
DOUBLEJEOPARDYA=5231
DRAGAMAW=5229
FIREWALKWITHMEA=5221
IMINTHEWHITELODGE=5219
SOARINGSPIRITSA=5213



--isle of conquest
RESOURCEGLUTH=4176
BACKDOORJOB=3854
CONQUESTVETERAN=3777
CONQUESTALLSTAR=3845
MINEH=4177
FOURCARGARAGE=3847
ABOMBINABLE=3848
ABOMBINATION=3849
MOWEDDOWN=3850
CUTTHEBLUEWIRE=3852
ALLOVERTHEISLE=3853
DEMOLITIONDERBYH=4256
GLAIVEGRAVE=3855
MASTERCONQUESTH=3957
RESOURCEGLUTA=3846
MINEA=3851
DEMOLITIONDERBYA=3856
MASTERCONQUESTA=3857
ISLEOFCONQUESTVICTORY=3776



--BATTLEFORGILNEAS
JUGGER=5255
GILNEASVICTORY=5245
GILNEASVETERAN=5246
GILNEASEPERFECTION=5247
BUSTINCAPSTOMAKEITHAPS=5248
ONETWOTHREEYOUDONTKNOWABOUTME=5249
OUTOFTHEFOG=5250
NOTYOURAVERAGEPUGER=5251
DONTGETCOCKYKID=5252
FULLCOVERAGE=5253
NEWBSTOPLOWSHARES=5254
DOUBLERAINBOW=5262
GILNEASALLSTAR=5256
GILNEASASSASSIN=5257
MASTEROFGILNEAS=5258



--pvp
WARSONGVICTORY=166
HONORABLEKILL=238
ARATHIVICTORY=154
HUNDREDKILLS=513
FIVEHUNDREDKILLS=515
THOUSANDKILLS=516
AVVICTORY=218
EOTSVICTORY=208
WGVICTORY=1717
IOCVICTORY=3776
BFGVICTORY=5245
TPVICTORY=5208
TBVICTORY=5412
KNOWTHYENEMYALLY=246
KNOWTHYENEMYHORDE=1005
MAKELOVE=247
GRIMREAPER=229
CAPTURETHEFLAG=199


FREEDOMOFALLIANCE=701
FREEDOMOFHORDE=700
DAMAGECONTROL=227
THATTAKESCLASS=245
CALLINTHECAVALRY=727
DUELICIOUS=1157
FIVETHOUSANDHONORABLEKILLS=512
CITYDEFENDER=1006
WRATHOFTHEHORDE=603
STORMINGSTORMWIND=615
OVERTHROWTHECOUNCIL=616
IMMORTALNOMORE=617
PUTTINGOUTTHELIGHT=618
FORTHEHORDE=619
THECONQUEROR=714
CALLTOARMS=909
WRECKINGBALL=231
GRIZZLEDVETERAN=2017
BATTLEMASTER=1175

--AB
DISGRACINTHEBASIN=73
LETSGETTHISDONE=159
ARATHIBASINASSASSIN=584
ARATHIBASINPERFECTION=165
OVERLYDEFENSIVE=1153
ARATHIBASINVETERAN=155
MEANDTHECAPPINMAKINGITHAPPEN=158
ARATHIBASINALLSTAR=583
MASTEROFARATHIBASIN=1169
WEHADITALLALONG=162
TOTHERESCUE=157
RESILIENTVICTORY=161
TERRITORIALDOMINANCE=156
THEDEFILER=710
KNIGHTOFARATHOR=711



--warsong
WGPERFECTION=168
NOTINMYHOUSEA=203
NOTINMYHOUSEH=1251
NOTSOFAST=1259
SAVETHEDAY=207
WARSONGEXPEDIENCE=201
QUICKCAPA=202
QUICKCAPH=1502
WGVETERAN=167
PERSISTENTDEFENDER=200
FRENZIEDDEFENDER=872
SUPREMEDEFENDERA=206
SUPREMEDEFENDERH=1252
IRONMAN=204
SILVERWINGSENTINEL=713
MASTEROFWG=1172
WARSONGOUTRIDER=712


--eots
STORMCAPPER=212
TAKEACHILLPILL=1258
STORMYASSASSIN=587
EOTSVETERAN=209
PERFECTSTORM=783
EOTSDOMINATION=784
FLURRY=214
STORMTROOPER=213
BOUNDFORGLORY=216
BLOODTHIRSTYBERSERKER=233
STORMGLORY=211
MASTEROFEOTS=1171

--rated bg
INSERVICEOFTHEHORDE=5269 --others also
VETERANOFTHEHORDE=5325 -- oothers also
SCOUT=5345
GRUNT=5346
SERGEANTH=5347
SENIORSERGEANT=5348
FIRSTSERGEANT=5349
STONEGUARD=5350
BLOODGUARD=5351
LEGIONNAIRE=5352
CENTURION=5338
CHAMPION=5353
LIEUTENANTGENERAL=5354
GENERAL=5355
WARLORD=5342
HIGHWARLORD=5356
HEROOFTHEHORDE=6941
--and for alliance
INSERVICEOFTHEALLIANCE=5268 --others also
VETERANOFTHEALLIANCE=5328 --others also
PRIVATE=5330
CORPORAL=5331
SERGEANTA =5332
MASTERSERGEANT=5333
SERGEANTMAJOR=5334
KNIGHT=5335
KNIGHTLIEUTENANT=5336
KNIGHTCAPTAIN=5337
KNIGHTCHAMPION=5359
LIEUTENANTCOMMANDER=5339
COMMANDER=5340
MARSHAL=5341
FIELDMARSHAL=5357
GRANDMARSHAL=5343
HEROOFTHEALLIANCE=6942


--tol barad achs
TOLBARADVICTORY=5412
JUSTANOTHERDAYINTOLBARADH=5719
TOLBARADVETERANH=5418
TOWERPLOWER=5415
TOWERSOFPOWER=5488
TOLBARADSABOTEUR=5487
TOLBARADALLSTAR=5486
PITLORDARGALOTH=5416
OCCUTHAR=6045
ALIZABAL=6108
MASTEROFTOLBARADH=5490
JUSTANOTHERDAYINTOLBARADA=5718
TOLBARADVETERANA=5417
MASTEROFTOLBARADA=5489

--WINTERGRASP
BLACKWARMAMMOTH=2080
TORAVON10=4585
DESTRUCTIONDERBYH=2476
DESTRUCTIONDERBYA=1737
WINTERGRASPVETERAN=1718
WITHINOURGRASP=1755
WINTERGRASPRANGER=2199
VEHICULARGNOMESLAUGHTER=1723
LEANINGTOWER=1727
DIDNTSTANDACHANCE=1751
ARCHAVON10=1722
ARCHAVON25=1721
EMALON10=3136
EMALON25=3137
KORALON10=3836
KORALON25=3837
TORAVON25=4586
MASTEROFWINTERGRASP=1752


--temple
KOTMOGUVICTORY=6740
FOURSQUARE=6947
POWERBALL=6950
BLACKOUT=6970
CANTSTOPWONTSTOP=6973
IVEGOTTHEPOWER=6971
WHATISBESTINLIFE=6972
KOTMOGUALLSTAR=6980
MASTEROFKOTMOGU=6981
KOTMOGUVETERAN=6882

KOTMOGUACHS = {}
KOTMOGUACHS[KOTMOGUVICTORY] = 10
KOTMOGUACHS[FOURSQUARE] = 10
KOTMOGUACHS[POWERBALL] = 10
KOTMOGUACHS[BLACKOUT] = 10
KOTMOGUACHS[CANTSTOPWONTSTOP] = 10
KOTMOGUACHS[IVEGOTTHEPOWER] = 10
KOTMOGUACHS[WHATISBESTINLIFE] = 10
KOTMOGUACHS[KOTMOGUALLSTAR] = 10
KOTMOGUACHS[MASTEROFKOTMOGU] = 10
KOTMOGUACHS[KOTMOGUVETERAN] = 10

--deepwindgorge
CAPPINGSPREE=8359
DEEPWINDGORGEALLSTAR=8358
DEEPWINDGORGEPERFECTION=8333
DEEPWINDGORGEVETERAN=8332
DEEPWINDGORGEVICTORY=8331
MASTEROFDEEPWINDGORGE=8360
MINEMINEMINE=8350
OTHERPEOPLESPROPERTY=8351
PUDDLEJUMPER=8354
WEIGHEDDOWN=8355

--SILVERSHARD
ENDOFTHELINE=7057
ESCORTSERVICE=7102
FIVEFORFIVE=7099
GREEDISGOOD=7103
MASTEROFSILVERSHARDMINES=7106
MINECARTCOURIER=7049
MINEMINEMINESS=7062
MYDIAMANDSANDYOURRUST=7100
SILVERSHARDMINESVETERAN=6883
SILVERSHARDMINESVICTORY=6739
LONGRIDERS=7039

--generic
KHANA=8052
KHANH=8055
CANDLEKEEPER=8717
EMISSARYOFORDOS=8716
FIREWATCHER=8721
KILNMASTER=8720
OATHGUARD=8718

--good to sort by battleground so can display only those when in bg

LEVELTENPVPACHIEVEMENTS = {}
LEVELTENPVPACHIEVEMENTS[CALLINTHECAVALRY] = 10
LEVELTENPVPACHIEVEMENTS[DUELICIOUS] = 60 -- SIMPLY don't care for it
LEVELTENPVPACHIEVEMENTS[MAKELOVE] = 20
LEVELTENPVPACHIEVEMENTS[GRIMREAPER] = 20
LEVELTENPVPACHIEVEMENTS[DAMAGECONTROL] = 60
LEVELTENPVPACHIEVEMENTS[THATTAKESCLASS] = 60
LEVELTENPVPACHIEVEMENTS[WRECKINGBALL]= 60
LEVELTENPVPACHIEVEMENTS[BATTLEMASTER] = 80
LEVELTENPVPACHIEVEMENTS[CANDLEKEEPER] = 80
LEVELTENPVPACHIEVEMENTS[EMISSARYOFORDOS] = 80
LEVELTENPVPACHIEVEMENTS[FIREWATCHER] = 80
LEVELTENPVPACHIEVEMENTS[KILNMASTER] = 90 --timeless isle
LEVELTENPVPACHIEVEMENTS[OATHGUARD] = 90 --timeless isle


WARSONGGULCHACH = {}
WARSONGGULCHACH[WARSONGVICTORY] = 15
WARSONGGULCHACH[WGPERFECTION] = 20
WARSONGGULCHACH[NOTSOFAST] = 70 -- random cah
WARSONGGULCHACH[WARSONGEXPEDIENCE] = 70 -- randomach
WARSONGGULCHACH[SAVETHEDAY] = 70 -- random ach
WARSONGGULCHACH[CAPTURETHEFLAG] = 30
WARSONGGULCHACH[WGVETERAN] = 70 -- longhaul
WARSONGGULCHACH[SUPREMEDEFENDERA] = 70
WARSONGGULCHACH[SUPREMEDEFENDERH] = 70
WARSONGGULCHACH[PERSISTENTDEFENDER] = 70
WARSONGGULCHACH[FRENZIEDDEFENDER] = 70 --random ach.  would be good to show them in bg only
WARSONGGULCHACH[QUICKCAPA] = 70
WARSONGGULCHACH[QUICKCAPH] = 70
WARSONGGULCHACH[NOTINMYHOUSEA] = 70 -- random ach
WARSONGGULCHACH[NOTINMYHOUSEH] = 70 -- random ach
WARSONGGULCHACH[IRONMAN] = 70
WARSONGGULCHACH[MASTEROFWG] = 70 -- aggregate


PVPALLIANCEACHIEVEMENTS = {}
PVPALLIANCEACHIEVEMENTS[KNOWTHYENEMYALLY] = 20
PVPALLIANCEACHIEVEMENTS[FREEDOMOFALLIANCE] = 20 -- not on monk.  annoying.
PVPALLIANCEACHIEVEMENTS[SILVERWINGSENTINEL] = 70 --very long haul. Also WG
PVPALLIANCEACHIEVEMENTS[KNIGHTOFARATHOR] = 70 
PVPALLIANCEACHIEVEMENTS[KHANA] = 90 


PVPHORDEACHS = {}--
PVPHORDEACHS[FROSTWOLFHOWLER] = 60 
PVPHORDEACHS[HEROOFFROSTWOLF] = 60
PVPHORDEACHS[WARSONGOUTRIDER] = 60
PVPHORDEACHS[KNOWTHYENEMYHORDE] = 20
PVPHORDEACHS[FREEDOMOFHORDE] = 20
PVPHORDEACHS[KHANH] = 90



ARATHIBASINACH = {}
ARATHIBASINACH[ARATHIVICTORY] =15
ARATHIBASINACH[DISGRACINTHEBASIN] = 15
ARATHIBASINACH[LETSGETTHISDONE] =70 --random ach
ARATHIBASINACH[ARATHIBASINASSASSIN] =15
ARATHIBASINACH[ARATHIBASINPERFECTION] =70-- random ach
ARATHIBASINACH[OVERLYDEFENSIVE] =15
ARATHIBASINACH[ARATHIBASINVETERAN] =70 -- long haul
ARATHIBASINACH[MEANDTHECAPPINMAKINGITHAPPEN] =60 
ARATHIBASINACH[ARATHIBASINALLSTAR] = 60 -- random, but not impossible
ARATHIBASINACH[MASTEROFARATHIBASIN] = 70
ARATHIBASINACH[WEHADITALLALONG] = 70
ARATHIBASINACH[TOTHERESCUE] = 60
ARATHIBASINACH[RESILIENTVICTORY] = 60
ARATHIBASINACH[TERRITORIALDOMINANCE] = 60
ARATHIBASINACH[THEDEFILER] =70


EOTSACH = {}
EOTSACH[TAKEACHILLPILL] = 20
EOTSACH[STORMCAPPER] = 20
EOTSACH[EOTSVICTORY] = 20
EOTSACH[EOTSVETERAN] =55
EOTSACH[EOTSDOMINATION] = 55
EOTSACH[STORMYASSASSIN] = 30
EOTSACH[MASTEROFEOTS] = 60
EOTSACH[STORMGLORY] = 65
EOTSACH[PERFECTSTORM] = 65

--tricky EOTS achievements
EOTSACH[BOUNDFORGLORY] = 60
EOTSACH[BLOODTHIRSTYBERSERKER] = 60
EOTSACH[STORMTROOPER] = 60
EOTSACH[FLURRY] = 65


AVACH = {}
AVACH [EVERYTHINGCOUNTS] = 50
AVACH [ALTERACBLITZ] = 50
AVACH [TOTHELOOTERGOTHESPOILS] = 50
AVACH[AVVICTORY] = 45
AVACH[SICKLYGAZELLE] = 45
AVACH[AVVETERAN] = 60
AVACH[FROSTWOLFPERFECTION] = 60
AVACH[AVALLSTAR] = 60
AVACH[ALTERACGRAVEROBBER] = 60
AVACH[TOWERDEFENSE] = 60
AVACH[LOYALDEFENDER] = 60
AVACH[MASTEROFAV] = 60
AVACH[EVERYTHINGCOUNTSA] =60
AVACH[LOYALDEFENDERA] =60
AVACH[STORMPIKEPERFECTION]=60
AVACH[STORMPIKEBATTLECHARGER]=60
AVACH[HEROOFTHESTORMPIKEGUARD]=60


--arena. min level 70.  prob needs to be on random timer

ARENAACHS = {}
ARENAACHS[STEPINTOTHEARENA] = 70
ARENAACHS[WORLDWIDEWINNER] = 70
ARENAACHS[JUSTTHETWOOFUS] = 70
ARENAACHS[THREESCOMPANY] = 70
ARENAACHS[HIGHFIVE] = 70
ARENAACHS[HOTSTREAK] = 70
ARENAACHS[HOTTERSTREAK] = 70
ARENAACHS[LASTMANSTANDING] = 70
ARENAACHS[CHALLENGER] = 70
ARENAACHS[RIVAL] = 70
ARENAACHS[DUELIST] = 70
ARENAACHS[GLADIATOR] = 70
ARENAACHS[ARENAMASTER] = 70

STRANDACHS = {}
STRANDACHS[ARTILLERYEXPERT]= 50
STRANDACHS[STRANDOFTHEANCIENTSVETERAN]= 50
STRANDACHS[STORMTHEBEACH]= 50
STRANDACHS[STEADYHANDS]= 50
STRANDACHS[DEFENSEOFTHEANCIENTSH]= 50
STRANDACHS[DEFENSEOFTHEANCIENTSA]= 50
STRANDACHS[DAPPERSAPPER]= 50
STRANDACHS[EXPLOSIVESEXPERT]= 50
STRANDACHS[NOTEVENASCRATCHH]= 50
STRANDACHS[NOTEVENASCRATCHA]= 50
STRANDACHS[ARTILLERYVETERAN]= 50
STRANDACHS[DROPIT]= 50
STRANDACHS[DROPITNOW]= 50
STRANDACHS[ANCIENTPROTECTOR]= 50
STRANDACHS[ANCIENTCOURTYARDPROTECTOR]= 50
STRANDACHS[MASTEROFSTRANDOFTHEANCIENTS]= 50
STRANDACHS[STRANDOFTHEANCIENTSVICTORY] = 50


GILNEASACHS = {}
GILNEASACHS[JUGGER] = 25
GILNEASACHS[GILNEASVICTORY] = 25
GILNEASACHS[GILNEASVETERAN] = 25
GILNEASACHS[GILNEASEPERFECTION] = 25
GILNEASACHS[BUSTINCAPSTOMAKEITHAPS] = 25
GILNEASACHS[ONETWOTHREEYOUDONTKNOWABOUTME] = 25
GILNEASACHS[OUTOFTHEFOG] = 25
GILNEASACHS[NOTYOURAVERAGEPUGER] = 25
GILNEASACHS[DONTGETCOCKYKID] = 25
GILNEASACHS[FULLCOVERAGE] = 25
GILNEASACHS[NEWBSTOPLOWSHARES] = 25
GILNEASACHS[DOUBLERAINBOW] = 25
GILNEASACHS[GILNEASALLSTAR] = 25
GILNEASACHS[GILNEASASSASSIN] = 25
GILNEASACHS[MASTEROFGILNEAS] = 25

TWINPEAKSACHS = {}
TWINPEAKSACHS[TWINPEAKSPERFECTION] = 25
TWINPEAKSACHS[WILDHAMMERING] = 25
TWINPEAKSACHS[TWINPEAKING] = 25
TWINPEAKSACHS[TWOTIMER] = 25
TWINPEAKSACHS[TOPDEFENDER] = 25
TWINPEAKSACHS[SOARINGSPIRITSH] = 25
TWINPEAKSACHS[PEAKSPEED] = 25
TWINPEAKSACHS[CLOUDNINEH] = 25
TWINPEAKSACHS[IMINTHEBLACKLODGE] = 25
TWINPEAKSACHS[FIREWALKWITHMEH] = 25
TWINPEAKSACHS[TWINPEAKSMOUNTAINEER] = 25
TWINPEAKSACHS[DOUBLEJEOPARDYH] = 25
TWINPEAKSACHS[MASTEROFTWINPEAKS] = 25
TWINPEAKSACHS[CLOUDNINEA] = 25
TWINPEAKSACHS[DOUBLEJEOPARDYA] = 25
TWINPEAKSACHS[DRAGAMAW] = 25
TWINPEAKSACHS[FIREWALKWITHMEA] = 25
TWINPEAKSACHS[IMINTHEWHITELODGE] = 25
TWINPEAKSACHS[SOARINGSPIRITSA] = 25



DEEPWINDGORGEACHS ={}
DEEPWINDGORGEACHS[CAPPINGSPREE] = 40
DEEPWINDGORGEACHS[DEEPWINDGORGEALLSTAR] = 40
DEEPWINDGORGEACHS[DEEPWINDGORGEPERFECTION] = 40
DEEPWINDGORGEACHS[DEEPWINDGORGEVETERAN] = 40
DEEPWINDGORGEACHS[DEEPWINDGORGEVICTORY] = 40
DEEPWINDGORGEACHS[MASTEROFDEEPWINDGORGE] = 40
DEEPWINDGORGEACHS[MINEMINEMINE] = 40
DEEPWINDGORGEACHS[OTHERPEOPLESPROPERTY] = 40
DEEPWINDGORGEACHS[PUDDLEJUMPER] = 40
DEEPWINDGORGEACHS[WEIGHEDDOWN] = 40

SILVERSHARDACHS = {}
SILVERSHARDACHS[ENDOFTHELINE]= 40
SILVERSHARDACHS[ESCORTSERVICE]= 40
SILVERSHARDACHS[FIVEFORFIVE]= 40
SILVERSHARDACHS[GREEDISGOOD]= 40
SILVERSHARDACHS[MASTEROFSILVERSHARDMINES]= 40
SILVERSHARDACHS[MINECARTCOURIER]= 40
SILVERSHARDACHS[MINEMINEMINESS]= 40
SILVERSHARDACHS[MYDIAMANDSANDYOURRUST]= 40
SILVERSHARDACHS[SILVERSHARDMINESVETERAN]= 40
SILVERSHARDACHS[SILVERSHARDMINESVICTORY]= 40
SILVERSHARDACHS[LONGRIDERS]= 40






--battlegrounds by minimum level

BGMINLEVEL = {}
BGMINLEVEL[WARSONGGULCH] = 10
BGMINLEVEL[ARATHIBASIN] = 10
BGMINLEVEL[EOTS] = 15
BGMINLEVEL[ALTERACVALLEY] = 20
BGMINLEVEL[STRANDOFTHEANCIENTS] = 50
BGMINLEVEL[ISLEOFCONQUEST] =55
BGMINLEVEL[TWINPEAKS] = 30
BGMINLEVEL[BATTLEFORGILNEAS] = 25
BGMINLEVEL[TEMPLEOFKOTMOGU] = 40
BGMINLEVEL[SILVERSHARDMINES] = 35
BGMINLEVEL[DEEPWINDGORGE] = 45
BGMINLEVEL[WINTERGRASP] = 75
BGMINLEVEL[TOLBARAD] = 80
BGMINLEVEL[ARENA]=25
